### ISSUE TITLE
There is a problem displaying local images in the local MD

### ISSUE THREAD

**Issue by bawangse** [asjqkkkk/markdown_widget#101]
I use Flutter to read local MD, which contains local images and is imported through relative paths, such as! [vscode] (./img/vscode git source repeat. png), so the image will not be displayed. May I know what to do

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/236465543-e5f93c3a-9444-4c3c-bf78-73d2961b5b7c.png)

Hi @bawangse , the example shows the usage for local images, maybe it can hlep you to solve this issue

**Comment by bawangse** [comment]
Is this' assets' set in pubspec.yaml?

My images are stored in the built-in storage, not in the text application directory, such as/store/mutated/0/knowledge/docs/wiki/img/vscode git source repeat. png.

How should I set this up?

I can't even try the following:

```

assets:

- /storage/emulated/0/aknow/docs/wiki/img/vscode-git-source-repeat.png

- /storage/emulated/0/aknow/docs/wiki/img

```

Inside MD: [] (/storage/mutated/0/knowledge/docs/wiki/img/vscode git source repeat. png)

**Comment by asjqkkkk** [comment]
Hi @bawangse , if that's the case, you may need to refer to the implementation here [img.dart](https://github.com/asjqkkkk/markdown_widget/blob/master/lib/widget/inlines/img.dart), you need to implement your own ImageNode and you need to distinguish between local URLs and choose different loading methods, such as FileImage, AssetImage, or NetworkImage.

**Comment by asjqkkkk** [comment]
Sorry, I forgot that using `ImgBuilder` with `ImgConfig` can achieve the same effect more easily.
