### ISSUE TITLE
选择文字后Ctrl+C复制有时无法复制文字

### ISSUE THREAD

**Issue by DogeVenci** [asjqkkkk/markdown_widget#103]
windows平台 选择文字后Ctrl+C复制有时无法复制文字 要按几次Ctrl+C或右键选择copy才能复制到剪贴板
另外希望增加能自定义快捷键的方法

**Comment by asjqkkkk** [comment]
@DogeVenci 你好，这应该是一个 flutter SelectionArea的问题，可以参考这里 https://github.com/flutter/flutter/issues/104549

这个问题需要等待flutter修复，目前我使用的是stable 3.3.1版本，似乎没有遇到这个情况，可以参考一下

**Comment by asjqkkkk** [comment]
关于“自定义快捷键”的方法，是指响应键盘某些按键输入吗？

**Comment by TaceBK** [comment]
> @DogeVenci 你好，这应该是一个 flutter SelectionArea的问题，可以参考这里 [flutter/flutter#104549](https://github.com/flutter/flutter/issues/104549)
> 
> 这个问题需要等待flutter修复，目前我使用的是stable 3.3.1版本，似乎没有遇到这个情况，可以参考一下

这个的意思是，取消全局的selectionarea就可以了是么

**Comment by asjqkkkk** [comment]
> 

不是，正是因为加上selectionarea才可以全局复制，而目前selectionarea是存在一些bug的，这需要等待flutter官方来修复
