### ISSUE TITLE
Code highlighting of type root always show in color black

### ISSUE THREAD

**Issue by Taewan-P** [asjqkkkk/markdown_widget#104]
**Describe the bug**

Code highlighting of type root always show in color black. No matter what theme I apply, the root type of the text will always be black, even though the theme explicitly sets the color to white.

**To Reproduce**
<img width="589" alt="image" src="https://github.com/asjqkkkk/markdown_widget/assets/27392567/9f8318a5-ab28-4ecd-ab99-39a3d03dcde5">

I applied the dark theme from the `flutter_highlight-0.7.0`, and as you can see, the color of the type 'root' is white-like color.

However, by rendering the code from my app like this:

```dart
    codeWrapper(child, text) => CodeWrapperWidget(child: child, text: text);
    final mdGen = MarkdownGenerator(
        config: MarkdownConfig(configs: [
      PreConfig(
          decoration: const BoxDecoration(
              color: Color(0xff2a2a2a),
              borderRadius: BorderRadius.all(Radius.circular(8.0))),
          theme: a11yDarkTheme,
          textStyle: GoogleFonts.jetBrainsMono(
              textStyle: const TextStyle(fontSize: 12)),
          wrapper: codeWrapper),
    ]));

    return Column(
      children: mdGen.buildWidgets(data),
    );
```

It will show the root type text into black, resulting some missing texts from the screen.

<img width="399" alt="image" src="https://github.com/asjqkkkk/markdown_widget/assets/27392567/e9d8cad7-23ba-4ac9-8789-9cf27452a98a">

**Expected behavior**

Root type texts should be the color of the theme's value when the theme is set.

**Screenshots**

**Environment(please complete the following information):**
Please use `flutter doctor -v` to show your flutter environment, and add your `markdown_widget` version too
```
[✓] Flutter (Channel master, 3.10.0-2.0.pre.3, on macOS 13.3.1 22E772610a darwin-arm64, locale en-KR)
    • Flutter version 3.10.0-2.0.pre.3 on channel master at /Users/<usrname>/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aa6a0a9dea (5 weeks ago), 2023-04-07 06:52:30 +0200
    • Engine revision d1dad6acbe
    • Dart version 3.0.0 (build 3.0.0-417.0.dev)
    • DevTools version 2.23.1
   ```

markdown_widget version: `markdown_widget: ^2.1.0`

**Platform**
Does the problem appear on the **Web** or on the **Mobile**？

Mobile. Haven't tested in the Web since the project doesn't support web.

**Source data**
Please provide a minimal source data that can help locating the problem

**Comment by Taewan-P** [comment]
I've tried other theme as well, but it's same

**Comment by asjqkkkk** [comment]
Hi @Taewan-P , the logic for code highlighting is mainly in the highlight and flutter_highlight libraries. I am not quite clear on the parsing rules for the node colors configured in the theme, but if you want to modify the color corresponding to root, you can try the following:

```
    codeWrapper(child, text) => CodeWrapperWidget(child: child, text: text);
    final yourTheme = Map.of(a11yDarkTheme);
    yourTheme['root'] = TextStyle(...);
    final mdGen = MarkdownGenerator(
        config: MarkdownConfig(configs: [
          PreConfig(
              decoration: const BoxDecoration(
                  color: Color(0xff2a2a2a),
                  borderRadius: BorderRadius.all(Radius.circular(8.0))),
              theme: yourTheme,
              textStyle: GoogleFonts.jetBrainsMono(
                  textStyle: const TextStyle(fontSize: 12)),
              wrapper: codeWrapper),
        ]));
```

**Comment by Taewan-P** [comment]
@asjqkkkk I tried customizing the theme myself like you, but directly setting the theme like the code you showed here still didn't work... Any other ways like changing the highlighter...?

**Comment by asjqkkkk** [comment]
Hi @Taewan-P , here is a solution and I'll include it in the next version.
If you need to solve this problem urgently, you can refer to the code here [code_block.dart](https://github.com/asjqkkkk/markdown_widget/blob/dev/lib/widget/blocks/leaf/code_block.dart)
You need to use styleNotMatched to set the color for the code that is not matched with the theme, otherwise it will be the default color.

![image](https://github.com/asjqkkkk/markdown_widget/assets/30992818/22056dab-a83a-4258-9099-fb66eed61c84)

**Comment by Taewan-P** [comment]
@asjqkkkk Hi, thanks for the answer! I really appreciate how you actively maintain this library.
I'm not really in a hurry, but can I achieve the bugfix just by referring to the code you linked? I don't quite understand. I'm using 2.1.0, and the part you added seems like it doesn't exist in the version I'm using, and I can't just directly edit the library file from the .pub folder...right?

**Comment by asjqkkkk** [comment]
Hi @Taewan-P , there are two ways to implement this feature.

### First

The first one is to modify the dependency of `markdown_widget ` in the yaml file and use `styleNotMatched`.
```
  markdown_widget:
    git:
      url: https://github.com/asjqkkkk/markdown_widget.git
      ref: dev
```


### Second

The second one is to customize your own `CodeBlockNode` and implement `SpanNodeGeneratorWithTag` corresponding to the `pre` tag. You can refer to [code_block.dart](https://github.com/asjqkkkk/markdown_widget/blob/dev/lib/widget/blocks/leaf/code_block.dart) to implement it.

**Comment by Taewan-P** [comment]
@asjqkkkk 
Hi, Thanks for the detailed explanation! It helped me a lot.

**Comment by turbobuilt** [comment]
Having this issue too
<img width="361" alt="Screenshot 2024-03-10 at 10 20 42 PM" src="https://github.com/asjqkkkk/markdown_widget/assets/7775272/08d0074a-60be-4e3e-bdfc-0205de4266f7">

**Comment by turbobuilt** [comment]
Here we go!

```
      PreConfig.darkConfig.copy(styleNotMatched: TextStyle(color: Colors.white)),
```
