### ISSUE TITLE
Latex rendering with example code

### ISSUE THREAD

**Issue by NicolasLaube** [asjqkkkk/markdown_widget#106]
The latex rendering using the example code seems not to work when using multiple latex formulas.

This issue can be reproduced on the provided [editor](https://asjqkkkk.github.io/markdown_widget/#/editor).

Here are a few screen shots to illustrate:

Only one formula (works):
<img width="679" alt="image" src="https://github.com/asjqkkkk/markdown_widget/assets/45005101/3fe344c3-5af0-4597-844e-dc99ba3e5b84">

Tow formulas (doesn't work):
<img width="860" alt="image" src="https://github.com/asjqkkkk/markdown_widget/assets/45005101/f34be837-91d8-4a64-bde7-6c7684c887cf">

**Comment by asjqkkkk** [comment]
Hi @NicolasLaube , the `markdown_widget` does not support rendering of Latex by default, so it is only shown as an extended example. 
Currently, the logic for filtering Latex content through regular expressions is not sufficient, and it may require a regex expert to complete this part. 
However, the expression in `LatexSyntax` can be replaced with the following:
```
r'(\$\$[\s\S]+\$\$)|(\$.+?\$)'
```
This can filter multiple expressions in a single line, although it may cause errors for content like this:
```
$\$$
```
![image](https://github.com/asjqkkkk/markdown_widget/assets/30992818/f5a74149-4622-4ca4-993b-a05bf6202c93)

**Comment by asjqkkkk** [comment]
Hi @NicolasLaube , this issue was fixed in v2.2.0, but as mentioned above, it introduced a new problem. 
However, I believe that other issues related to `Latex` are not truly related to the `markdown_widget`.
