### ISSUE TITLE
Markdown Generator Throws an `debugCannotComputeDryLayout` Error in certain texts

### ISSUE THREAD

**Issue by Taewan-P** [asjqkkkk/markdown_widget#107]
**Describe the bug**

When I put certain markdown text into Markdown generator, it throws `debugCannotComputeDryLayout` Error.

**To Reproduce**

1. Define markdown string 

```
The installation process for Python may vary depending on your operating system. Here are the steps to install Python on a Windows computer:\n\n1. Go to the official Python website: https://www.python.org/downloads/\n2. Click the \"Download Python\" labelLarge for the latest stable release.\n3. Scroll down and select the Windows installer appropriate for your system architecture (32-bit or 64-bit).\n4. Run the installer file once it's downloaded.\n5. On the first screen, make sure to select \"Add Python X.Y to PATH\" (where X.Y is the version you are installing) and choose the \"Customize installation\" option.\n6. On the next screen, make sure that all the optional features that you need are selected.\n7. Choose the default installation directory or any directory of your choice.\n8. Hit the Install button and wait for the installation process to finish. \n\nOnce the installation is completed, you can verify that Python has been installed by opening the command prompt or terminal and typing \"python\" followed by Return. If Python is installed correctly, you should see the version number displayed.
```

This is the exact text that I put that threw the error.

2. Generate Markdown
3. When rendering markdown, it throws an error

**Expected behavior**

It should not throw the error

**Screenshots**

Where the error is thrown

<img width="861" alt="image" src="https://github.com/asjqkkkk/markdown_widget/assets/27392567/cdcd7d4a-e2f3-4e64-8b12-c86e30ed3707">

**Environment(please complete the following information):**
Please use `flutter doctor -v` to show your flutter environment, and add your `markdown_widget` version too

```
[✓] Flutter (Channel master, 3.10.0-2.0.pre.3, on macOS 13.3.1 22E772610a darwin-arm64, locale en-KR)
    • Flutter version 3.10.0-2.0.pre.3 on channel master at /Users/<usrname>/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aa6a0a9dea (5 weeks ago), 2023-04-07 06:52:30 +0200
    • Engine revision d1dad6acbe
    • Dart version 3.0.0 (build 3.0.0-417.0.dev)
    • DevTools version 2.23.1
```

`markdown_widget: ^2.2.0`
    

**Platform**
Does the problem appear on the **Web** or on the **Mobile**？

Mobile 

**Source data**
Please provide a minimal source data that can help locating the problem

I have a markdown builder function defined like this:

```dart
  Widget markdownBuilder(String data) {
    codeWrapper(child, text) => CodeWrapperWidget(child: child, text: text);
    final myTheme = Map.of(a11yDarkTheme);
    myTheme['root'] = const TextStyle(color: Colors.white);
    final mdGen = MarkdownGenerator(
        config: MarkdownConfig(configs: []));

    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: mdGen.buildWidgets(data),
    );
```

Then I call the markdownBuilder to the Widget that I want to use.

```dart
double width = MediaQuery.of(context).size.width;
IntrinsicWidth(
      child: Container(
        constraints:
            BoxConstraints(minWidth: width * 0.6, maxWidth: width * 0.8),
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            markdownBuilder(content), // This is the where I put the String
            // Other widgets here
              ],
            ),
          ],
        ),
      ),
    );
```

It usually works right, but throws an error in that String specifically. Very weird. I'm assuming that it has  something to do with the numbered texts? (1. asdfasd 2. asfdasdf... )

**Comment by asjqkkkk** [comment]
Hi @Taewan-P , I'm not sure about the usage of `IntrinsicWidth`, but if you need to make Markdown adapt to its width, you can use `MarkdownBlock`, which is a new component added in version 2.2.0.

**Comment by Taewan-P** [comment]
Ah, I thought the other widgets in the children were irrelevant, so I did not write it down. 

`IntrinsicWidth` is used because one of the "Other widgets" in the Column has a Row widget which mainAxisAlignment is set to `spacebetween`.
So no matter what I do except using the `IntrinsicWidth`, it automatically maxes out to the maxWidth. 

What I would like to do is to set the parent width to minWidth, and as the markdownWidget gets bigger, it can max out to the maxWidth constraints.



```
double width = MediaQuery.of(context).size.width;
IntrinsicWidth(
      child: Container(
        constraints:
            BoxConstraints(minWidth: width * 0.6, maxWidth: width * 0.8),
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            markdownBuilder(content), // This is the where I put the String
            const Padding(
              padding: EdgeInsets.only(top: 6),
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                InkWell(
                  onTap: () {
                    final data = ClipboardData(text: content);
                    Clipboard.setData(data);
                  },
                  child: Text(
                    'Copy Text',
                    style: TextStyle(
                        color: lightColorScheme.secondary,
                        decoration: TextDecoration.underline),
                  ),
                ),
                Text(
                  'Powered by Provider',
                  style: TextStyle(color: lightColorScheme.secondary),
                ),
              ],
            ),
          ],
        ),
      ),
    );
   ```

**Comment by asjqkkkk** [comment]
Hi @Taewan-P , I think I roughly understand the reason behind it. In this example, there is an ordered list rendered within the [`ListNode`](https://github.com/asjqkkkk/markdown_widget/blob/96efd1a69c2439ed997e8804a567fb23ab017f85/lib/widget/blocks/container/list.dart#L59). The `Row` component used within `ListNode` by default has `mainAxisSize: MainAxisSize.max`, and the children by default have `Expand`. Next, I will modify them to `mainAxisSize: MainAxisSize.min` and `Flexible`.

**Comment by Taewan-P** [comment]
Hi @asjqkkkk . Thank you for your support.
