### ISSUE TITLE
How to set width of markdown_widget equal width of content  

### ISSUE THREAD

**Issue by vvviettt** [asjqkkkk/markdown_widget#108]
I have a markdown_widget , And I just want to display the content instead of it taking up all the available space.
<img width="322" alt="Screenshot 2023-05-21 at 17 55 50" src="https://github.com/asjqkkkk/markdown_widget/assets/97574971/5d120ba1-56ac-4e6b-9201-db067d205060">

Thank your for help.

**Comment by asjqkkkk** [comment]
Hi @vvviettt , you can use [`MarkdownBlock` ](https://github.com/asjqkkkk/markdown_widget/blob/master/lib/widget/markdown_block.dart)

**Comment by vvviettt** [comment]
> Hi @vvviettt , you can use [`MarkdownBlock` ](https://github.com/asjqkkkk/markdown_widget/blob/master/lib/widget/markdown_block.dart)

Thank you for help me :))
