### ISSUE TITLE
Handle the onTap event in the MarkdownBlock

### ISSUE THREAD

**Issue by xdidx** [asjqkkkk/markdown_widget#109]
**Is your feature request related to a problem? Please describe.**
I have issues with the onTap event of a button when I click on a MarkdownBlock inside it.

```
GestureDetector(
  onTap: () {
    print('Fired!');
  },
  child: const MarkdownBlock(
    data: 'Click on me !',
  ),
),
```

**Describe the solution you'd like**
Find a solution to make the parent event work (I don't know how) or just add an onPressed event on the MarkdownBlock.

**Comment by asjqkkkk** [comment]
Hi @xdidx , the `GestureDetector` will have a gesture conflict with the `SelectionArea`, you need to set `selectable` to `false` to solve this issue.

**Comment by xdidx** [comment]
Indeed... thank you !
