### ISSUE TITLE
有没有什么办法,去掉md中的格式符号,只保留文字

### ISSUE THREAD

**Issue by chen412115** [asjqkkkk/markdown_widget#115]
例如
```
# I'm h1
## I'm h2
### I'm h3
#### I'm h4
###### I'm h5
###### I'm h6
```
我想要的结果
I'm h1
I'm h2
I'm h3
I'm h4
I'm h5
I'm h6

**Comment by asjqkkkk** [comment]
@chen412115 你好，目前看到的现象是这样的
![image](https://github.com/asjqkkkk/markdown_widget/assets/30992818/77af84e3-da9f-4c7e-958a-85b1c029af03)

不太理解你描述的问题是否与当前现象一致，请具体的描述一下你希望的效果

**Comment by chen412115** [comment]
> 

我希望的效果是,我可以某个function,从md文本中获取到非格式化的文本
```
String input = '''
# I'm h1
## I'm h2
### I'm h3
#### I'm h4
###### I'm h5
###### I'm h6
''';

output = Utils.getXXX(input);
output:

I'm h1
I'm h2
I'm h3
I'm h4
I'm h5
I'm h6
```

**Comment by asjqkkkk** [comment]
@chen412115 
那其实这个问题与 `markdown_widget` 关系不太大
不过可以通过 [markdown](https://github.com/dart-lang/markdown) 库，将输入源转换为Node 列表，然后遍历Node去获取其中的text即可
