### ISSUE TITLE
Support for Dark Theme

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#12]
![Screenshot_20200422-094530](https://user-images.githubusercontent.com/44783405/79949705-9fcd5080-847e-11ea-9f48-0f814c13dff0.jpg)
![Screenshot_20200422-094517](https://user-images.githubusercontent.com/44783405/79949715-a4920480-847e-11ea-8e6c-00feebd23de3.jpg)

**Comment by asjqkkkk** [comment]
It's a good idea to support a default dark theme for markdown_widget, but I need to take the time to think about how to better implement this function. 
Before that, you can use `PreConfig` to customize the dark theme for your application
```
      styleConfig: StyleConfig(
        preConfig: PreConfig(
          decoration: BoxDecoration(
            color: codeBgColor,
            borderRadius: BorderRadius.all(
              Radius.circular(10),
            ),
          ),
          theme: isDark ? theme.darkTheme : theme.arduinoLightTheme,
        ),
      ),
```

**Comment by asjqkkkk** [comment]
now you can update to v1.1.2 to use dark theme😄

```
  Widget buildMarkdown() => MarkdownWidget(
        data: data,
        controller: controller,
        styleConfig: StyleConfig(
          markdownTheme: MarkdownTheme.lightTheme
        ),
      );
```

**Comment by asjqkkkk** [comment]
it should be `MarkdownTheme.darkTheme` 😂

**Comment by mrpvb-pvbk** [comment]
Cool! But, i think that the small distance between the some elements and the wrong angles of code blocs.
![Screenshot_20200422-190151](https://user-images.githubusercontent.com/44783405/80007343-cadf9080-84ce-11ea-92d0-76c17acee472.png)
![Screenshot_20200422-190209](https://user-images.githubusercontent.com/44783405/80007350-d0d57180-84ce-11ea-8e40-5db936fdf99b.png)
![Screenshot_20200422-1901511](https://user-images.githubusercontent.com/44783405/80007414-e21e7e00-84ce-11ea-999f-e9985ede3129.jpg)

**Comment by asjqkkkk** [comment]
> Cool! But, i think that the small distance between the some elements and the wrong angles of code blocs.
> ![Screenshot_20200422-190151](https://user-images.githubusercontent.com/44783405/80007343-cadf9080-84ce-11ea-92d0-76c17acee472.png)
> ![Screenshot_20200422-190209](https://user-images.githubusercontent.com/44783405/80007350-d0d57180-84ce-11ea-8e40-5db936fdf99b.png)
> ![Screenshot_20200422-1901511](https://user-images.githubusercontent.com/44783405/80007414-e21e7e00-84ce-11ea-999f-e9985ede3129.jpg)

maybe it's flutter's issue, you could have a try for [Online Demo](https://oldchen.top/markdown_widget/#/) with dark mode

**Comment by mrpvb-pvbk** [comment]
**I solved it!** 
Сhanged it
`childMargin: EdgeInsets.only(left: 10, right: 10),`
to this
`childMargin: EdgeInsets.all(10),`
