### ISSUE TITLE
此项目在渲染代码块时似乎没有调用等宽字体

### ISSUE THREAD

**Issue by Songyon** [asjqkkkk/markdown_widget#120]
**Describe the bug**
此项目在渲染代码块时似乎没有调用等宽字体，都是调用的系统默认非等宽字体

**To Reproduce**
Demo会这样，Readme的宣传图也会这样。

**Expected behavior**
我希望渲染代码块时使用等宽字体

**Platform**
全平台

**Comment by asjqkkkk** [comment]
@Songyon 你好，你可以通过 `PreConfig` 的 `textStyle` 来自定义你的字体

**Comment by Songyon** [comment]
> @Songyon 你好，你可以通过 `PreConfig` 的 `textStyle` 来自定义你的字体

好吧😢
