### ISSUE TITLE
Latex width overflow

### ISSUE THREAD

**Issue by wilinz** [asjqkkkk/markdown_widget#121]
**Describe the bug**
latex width overflow

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_2023-07-04-05-19-13-768_com example flutter_markdown](https://github.com/asjqkkkk/markdown_widget/assets/59408438/cce1be47-17d9-4f93-868b-987df4c01fdb

**Environment(please complete the following information):**
Please use `flutter doctor -v` to show your flutter environment, and add your `markdown_widget` version too

**Platform**
Mobile

**Source data**
Please provide a minimal source data that can help locating the problem

cloumn
  textfield
  expanded 
     markdown_widget

**Comment by wilinz** [comment]
设$f(x)$在$x=a$处有$n$阶连续导数，则对于$x$在$a$附近，
$$
f(x) = f(a) + f'(a)(x-a) + \frac{1}{2!}f''(a)(x-a)^2 + \frac{1}{3!}f'''(a)(x-a)^3 + \cdots + \frac{1}{n!}f^{(n)}(a)(x-a)^n + R_n
$$

其中，$R_n$为泰勒级数的剩余项，在$a$附近满足

$$
R_n(x) = \frac{1}{(n+1)!}f^{(n+1)}(c)(x-a)^{n+1}
$$
其中，$c$是在$a$和$x$之间某个值。

**Comment by wilinz** [comment]
![Uploading Screenshot_2023-07-04-05-37-19-578_com.example.flutter_markdown.jpg…]()

**Comment by asjqkkkk** [comment]
@wilinz 你好，`Latex` 表达式实际上不算`markdown_widget`的内容，它是作为 `markdown_widget` 扩展性的使用例子之一放入example的，如果你参考example使用了这个功能，可以修改 `LatexNode` 中build的widget，给它们加上一个横向的SingleChildScrollView

**Comment by wilinz** [comment]
okk
