### ISSUE TITLE
排版好像是有问题了，在线的demo是没有问题的，但是我运行后就有问题

### ISSUE THREAD

**Issue by homelee** [asjqkkkk/markdown_widget#126]
![image](https://github.com/asjqkkkk/markdown_widget/assets/3040122/c167803f-bdf2-497e-bb6a-029cc9099714)

**Comment by asjqkkkk** [comment]
@homelee 你好，请提供一下flutter doctor -v的信息，目前flutter web在3.10和部分其他版本上是会有问题的
