### ISSUE TITLE
Table contains irregular row lengths

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#13]
Caught by this md file: 
[12.markdown.txt](https://github.com/asjqkkkk/markdown_widget/files/4523771/12.markdown.txt)

Log:
```
Launching lib\main.dart on SM A605FN in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity(13380): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(13380): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(13380): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown building FutureBuilder<String>(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#b3b0e]], state: _FutureBuilderState<String>#faa7d):[39;49m
Table contains irregular row lengths.

[38;5;244mEvery TableRow in a Table must have the same number of children, so that every cell is filled. Otherwise, the table will contain holes.[39;49m
[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mFutureBuilder<String>[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      new Table.<anonymous closure>[39;49m
[38;5;244m#1      new Table[39;49m
[38;5;248m#2      MTable.getTableWidget[39;49m
[38;5;248m#3      MarkdownHelper.getTableWidget[39;49m
[38;5;248m#4      MarkdownGenerator._generatorWidget[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
I/flutter (13380): cpp

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
Table contains irregular row lengths.
[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mFutureBuilder<String>[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
```
Full log :
[log.txt](https://github.com/asjqkkkk/markdown_widget/files/4523783/log.txt)

My code:
```
MarkdownGenerator(
                            data: snapshot.data,
                            childMargin: EdgeInsets.only(left: 10, right: 10, top: 5, bottom: 5),
                            styleConfig: StyleConfig(
                               markdownTheme: (Theme.of(context).brightness == Brightness.dark) ? MarkdownTheme.darkTheme : MarkdownTheme.lightTheme,
                                preConfig: PreConfig(
                                    language: widget.sName,
                                    theme: (Theme.of(context).brightness == Brightness.dark) ? theme.vs2015Theme : theme.doccoTheme)))
                        .widgets
```

**Comment by asjqkkkk** [comment]
It looks like a table rows error,but I can't get the error log by using your sample

**Comment by mrpvb-pvbk** [comment]
I cant understand how its happens. Can u test it from SliverList?

**Comment by asjqkkkk** [comment]
😅I'm a little busy recently，Just wait a moment，I will check this issue later

**Comment by mrpvb-pvbk** [comment]
Any suggestions?

**Comment by asjqkkkk** [comment]
Will this problem occur now?
I am doing some preparations for my interview, so if you can provide😅
If you can provide more detailed information, then this problem can be quickly located and resolved

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/80951224-0d3b9280-8e2a-11ea-9a66-a107fbc62a7a.png)

It is MTable's bug，but I can't  reproduce this problem with your data

**Comment by mrpvb-pvbk** [comment]
Very strange. There TableRow problem.  I dont understand how i can solve it. I create gist https://gist.github.com/mrpvb-pvbk/c85fe6d2feb53bc883ecc506bccda5c2
Try it from my data.

**Comment by mrpvb-pvbk** [comment]
Yes! I solved this!) Look at this attachment
![Screenshot (1)](https://user-images.githubusercontent.com/44783405/80956954-e28e1180-8e0a-11ea-8003-c0989d9e736c.png)

**Comment by asjqkkkk** [comment]
> Yes! I solved this!) Look at this attachment
> ![Screenshot (1)](https://user-images.githubusercontent.com/44783405/80956954-e28e1180-8e0a-11ea-8003-c0989d9e736c.png)

can you provide the error data to me？😄

**Comment by mrpvb-pvbk** [comment]
So, how i can add '||' to the table?

**Comment by mrpvb-pvbk** [comment]
> > Yes! I solved this!) Look at this attachment
> > ![Screenshot (1)](https://user-images.githubusercontent.com/44783405/80956954-e28e1180-8e0a-11ea-8003-c0989d9e736c.png)
> 
> can you provide the error data to me？😄

[13.markdown.txt](https://github.com/asjqkkkk/markdown_widget/files/4574066/13.markdown.txt)
This

**Comment by asjqkkkk** [comment]
| Условие| Описание|
| --- | --- |
| a == 3  
&&  
b > 4| Составное условие истинно, если истинны оба простых условия.|
| a == 3  
||  
b > 4| Составное условие истинно, если истинно, хотя бы одно из простых условий.|
| !(a == 3)| Условие истинно, если a не равно 3.|

your data shows like this in github markdown
And I want to get the data that can cause this bug😂 not the right data

**Comment by mrpvb-pvbk** [comment]
No, it's bug data! Check this '||' in ur markdwn

**Comment by mrpvb-pvbk** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/44783405/80958053-09e5de00-8e0d-11ea-88ad-f7726c0601f0.png)
Check this

**Comment by asjqkkkk** [comment]
Ok, I found it! Wait for me to solve it😄

**Comment by asjqkkkk** [comment]
You can update to v1.1.4, this issue has been solved😄
