### ISSUE TITLE
Copy not enabled by default

### ISSUE THREAD

**Issue by luohao123** [asjqkkkk/markdown_widget#131]
Hi, I have a markdow widget using geneator likethis:

Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: MarkdownGenerator(
              linesMargin: EdgeInsets.zero,
              //  generators: [videoGeneratorWithTag, latexGenerator],,
              config: isDark
                  ? MarkdownConfig.darkConfig.copy(
                      configs: _getMarkdownConfigs(
                        isDark,
                        bodyTextStyle,
                        codeWrapper,
                      ),
                    )
                  : MarkdownConfig.defaultConfig.copy(
                      configs: _getMarkdownConfigs(
                        isDark,
                        bodyTextStyle,
                        codeWrapper,
                      ),
                    ),
            ).buildWidgets(message.text),
          ),

but the copy mode not ready default.

**Comment by asjqkkkk** [comment]
Hi @luohao123 , you need use `SelectionArea` to enable selecting

**Comment by luohao123** [comment]
thank u! every helpful!! I used SelectionArea it worked. But one moer quesiton.

SelectionArea(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: MarkdownGenerator(
                linesMargin: EdgeInsets.zero,
                generators: [videoGeneratorWithTag, latexGenerator],
                config: isDark
                    ? MarkdownConfig.darkConfig.copy(
                        configs: _getMarkdownConfigs(
                          isDark,
                          bodyTextStyle,
                          codeWrapper,
                        ),
                      )
                    : MarkdownConfig.defaultConfig.copy(
                        configs: _getMarkdownConfigs(
                          isDark,
                          bodyTextStyle,
                          codeWrapper,
                        ),
                      ),
              ).buildWidgets(message.text),
            ),
          ),


I using liek this, make the genreator like in your example folder, add latex and video support.

But

<img width="448" alt="image" src="https://github.com/asjqkkkk/markdown_widget/assets/49749220/104cd0bd-c1d6-426b-a9a0-98a709c7af1f">


latex not showing, is the format not right? The inline latex should showing

**Comment by asjqkkkk** [comment]
Hi @luohao123 , please provider the source data to locate the issue

**Comment by luohao123** [comment]
hello, the text is above text

**Comment by asjqkkkk** [comment]
@luohao123 you should also pass the `inlineSyntaxList: [LatexSyntax()]`

**Comment by luohao123** [comment]
@asjqkkkk hi,  MarkdownGenerator(
                linesMargin: EdgeInsets.zero,
                generators: [videoGeneratorWithTag, latexGenerator],
                inlineSyntaxList: [LatexSyntax()],


there is no such params in Generator

**Comment by asjqkkkk** [comment]
@luohao123 please have a look with https://github.com/asjqkkkk/markdown_widget/blob/master/example/lib/markdown_custom/latex.dart

you need to fetch the example code, then you'll konw how to use it
