### ISSUE TITLE
自定义标签中如果含有换行`\n`，标签就失效了

### ISSUE THREAD

**Issue by wzlsquall** [asjqkkkk/markdown_widget#135]
**自定义标签中如果含有换行`\n`，标签就失效了**
我自定义个标签`:::abcde:::`，如果本文中没有换行的话可以正常解析，但是如果含有换行`\n`就无法解析了。
例如：
:::abcde\nfg:::

**Comment by wzlsquall** [comment]
找到方法了

**Comment by Carlchk** [comment]
> 找到方法了

我遇上的情况跟你差不多，自定义标签中有\n\n，能请教一下如何处理吗？谢谢
