### ISSUE TITLE
RLT Support (Right to Left Languages like Hebrew, Arabic)

### ISSUE THREAD

**Issue by barak-innov** [asjqkkkk/markdown_widget#14]
Hi, do you have any support for RLT languages?

Thank you very much!

**Comment by asjqkkkk** [comment]
Flutter supports the configuration of international languages:
https://flutter.dev/docs/development/accessibility-and-localization/internationalization

I don't konw much about Right to Left Languages😂, could you provide some samples?

**Comment by asjqkkkk** [comment]
Hi, you can use `TextConfig` to set `textDirection` or use `flutter_localizations`

```
  flutter_localizations:
    sdk: flutter
```

that will support RTL languages

**Comment by AdnanAlshami** [comment]
> I don't konw much about Right to Left Languages😂, could you provide some samples?

take a look at this [repo](https://github.com/AdnanAlshami/markdown_test)

I added some images to explain the issue.

**Comment by asjqkkkk** [comment]
> > I don't konw much about Right to Left Languages😂, could you provide some samples?
> 
> take a look at this [repo](https://github.com/AdnanAlshami/markdown_test)
> 
> I added some images to explain the issue.

Hi, I'll take a look for this repo on Sunday

and I've provided `TextConfig` to support RTL in v1.2.0

![image](https://user-images.githubusercontent.com/30992818/87372373-f51a8900-c5b9-11ea-9b69-a2864a099ff0.png)

you can have a try for it

**Comment by AdnanAlshami** [comment]
> and I've provided `TextConfig` to support RTL in v1.2.0

using `textDirection` and `textAlign` is not enough to solve the problem.
I'm working on a PR, and I successfully fix some issues, but this gonna take some time since this is my very first PR ever.

**Comment by asjqkkkk** [comment]
This issue is too old, if necessary, please create an new issue
