### ISSUE TITLE
Getting get language error

### ISSUE THREAD

**Issue by rwctwo** [asjqkkkk/markdown_widget#142]
**Describe the bug**
I'm using MarkdownBlock and the data appears as expected, but I'm getting 'get language error: unexpected null value'. Is there any necessary configuration I need to set?

**Environment(please complete the following information):**

markdown_widget: ^2.3.2+1

[✓] Flutter (Channel stable, 3.16.4, on macOS 14.2 23C64 darwin-arm64, locale en-US)
    • Flutter version 3.16.4 on channel stable at /Users/thomasotani/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (3 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/thomasotani/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • Thomas iPhone 2020 SE (mobile) • 00008030-001468E826D1402E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)                • macos                     • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)                   • chrome                    • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Platform**
This is a web app.

**Source data**
Here's the build method:

```dart
Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Help Page', style: TextStyle(color: Colors.white)),
      ),
      body: Padding(
        padding: const EdgeInsets.all(10.0),
        child: MarkdownWidget(data: data),
      ),
   );
}
```

**Comment by LiuYimin** [comment]
@rwctwo Could you please tell me how you solved this problem?

**Comment by asjqkkkk** [comment]
Hi @rwctwo , this error is because your `PreConfig` passing the `null language`, this error will not include anything, and this print is only avaliable in debug mode
