### ISSUE TITLE
Please add Markdown editing toolbar

### ISSUE THREAD

**Issue by IsmailHosenIsmailJames** [asjqkkkk/markdown_widget#144]
There have lot of popular website. They use **Markdown for post, comment etc.** They have  **markdown editing tools**. For example GitHub have their own editing tools. Can you add that kind of tool bar where I can easily edit markdown text.
![Screenshot from 2023-12-16 11-06-54](https://github.com/asjqkkkk/markdown_widget/assets/99122172/cf2562fd-ea34-4045-904b-039c70cb983e)

**Comment by asjqkkkk** [comment]
Hi @IsmailHosenIsmailJames , thanks for your issue

The current functionality may have exceeded the scope of the `markdown_widget`. It is a capability that requires a significant amount of time and effort to implement. Currently, there are no plans to implement this feature, at least not in the `markdown_widget`, for an extended period of time.
