### ISSUE TITLE
desktop view can't render markdown image from link. But mobile view support.

### ISSUE THREAD

**Issue by IsmailHosenIsmailJames** [asjqkkkk/markdown_widget#146]
I have tried your package. I got a bug when I paste a simple markdown image with a https link. Desktop view was not able to render the image. The markdwon text was this :
```markdown
![Google Logo](https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png)
```

I also tried same thing in you demo page. Same things happen.

# these image from your demo page
![Screenshot from 2023-12-22 21-04-57](https://github.com/asjqkkkk/markdown_widget/assets/99122172/c822c03f-5e32-425b-9a42-0302f26f847f)

![Screenshot from 2023-12-22 21-05-49](https://github.com/asjqkkkk/markdown_widget/assets/99122172/4c7dd26a-5bb7-487e-aa18-5b8c3ecbfce6)
![Screenshot from 2023-12-22 21-04-57](https://github.com/asjqkkkk/markdown_widget/assets/99122172/c924f559-b13a-48fc-b4d1-1c5305edd949)

# this is my code
```dart
Row(
        children: [
          Expanded(
            child: TocWidget(controller: tocController),
          ),
          Expanded(
            child: MarkdownWidget(
              data: widget.markdown,
              tocController: tocController,
            ),
          ),
        ],
      ),
```
## here is the image
![Screenshot from 2023-12-22 21-05-45](https://github.com/asjqkkkk/markdown_widget/assets/99122172/c54317c6-134c-40af-848e-bb07b44c73c4)

**Comment by asjqkkkk** [comment]
Hi @IsmailHosenIsmailJames , this is a CORS issue on web

<img width="1137" alt="image" src="https://github.com/asjqkkkk/markdown_widget/assets/30992818/c6f45023-dc5d-4ebc-9f60-025c30558480">

**Comment by IsmailHosenIsmailJames** [comment]
But I have got a solution. The solution is to compile  with html for web render.
This is the command for compiled with html render: 
```
flutter build web --web-renderer html
```

**Comment by IsmailHosenIsmailJames** [comment]
i run this command for run your project with html renderer 
```
ismail@ismail:~/markdown_widget/example$ flutter run -d chrome --web-renderer html
```
then it works perfectly.
here is the image
![Screenshot from 2023-12-22 22-09-54](https://github.com/asjqkkkk/markdown_widget/assets/99122172/abf6703c-5da8-474c-9069-6e058dc48368)

**Comment by asjqkkkk** [comment]
> But I have got a solution. The solution is to compile with html for web render. This is the command for compiled with html render:
> 
> ```
> flutter build web --web-renderer html
> ```

yes, but this solution will cause many other abnormal behaviors
if you want to show the network images on web, you need change your the image server settings to support CORS
such as this picture: `![](https://img2.baidu.com/it/u=2546290954,811864095&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=281)`
<img width="1089" alt="image" src="https://github.com/asjqkkkk/markdown_widget/assets/30992818/971a3bb8-4324-4f14-8320-5b7cad87c1c6">

**Comment by IsmailHosenIsmailJames** [comment]
I actually building and social paltfrom where my students and my classmates will learn programming and will post here to share with others the learning resources. For this I am using Firebase as backend. User will upload their images and videos here. So I have no option to change my server settings to support this kind of images on my website. No problem I will compile it with HTML Render. because I previously using this for my website. Because Html render is light weight for my website.

**Comment by IsmailHosenIsmailJames** [comment]
I want to **work with you on open source projects**. For that I need to understand your code. Do you consider me?

**Comment by asjqkkkk** [comment]
Hi @IsmailHosenIsmailJames , using HTML as a rendering option may be lighter, but since it's just a fallback option for Flutter web, I may not have the time or ability to address the issues it may cause. If you encounter any issues with this open-source library, feel free to raise an issue anytime. I will review them when I have time and provide answers within my capabilities.
