### ISSUE TITLE
MarkdownBlock incorrect behaviour inside CupertinoAlertDialog

### ISSUE THREAD

**Issue by Time2HackJS** [asjqkkkk/markdown_widget#147]
Hi, i'm using MarkdownBlock inside CupertinoAlertDialog and getting unusual behaviour of text inside unordered list elements.

![test](https://github.com/asjqkkkk/markdown_widget/assets/48493929/5f3be3df-6529-4728-908d-a376f8df86e8)

There's no problem in regular alert dialog, but i need to align text properly exactly in cupertino alert dialog.

Here's the code i'm using.

```
const String checkText = '''
## Hello:
- 1
- 2
- 3
- This is a very long test text which i want to show you
I'm sad :(
''';

class TextMarkdownDialog extends StatelessWidget {
  final void Function(String url)? onOpenUrl;

  const TextMarkdownDialog({
    super.key,
    required this.onOpenUrl,
  });

  @override
  Widget build(BuildContext context) {
    return CupertinoAlertDialog(
      content: SingleChildScrollView(
        child: MarkdownBlock(
          data: checkText,
          config: MarkdownConfig(
            configs: [
              if (onOpenUrl != null)
                LinkConfig(
                  onTap: (url) => onOpenUrl?.call(url),
                ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by asjqkkkk** [comment]
Hi @Time2HackJS , do not use `CupertinoAlertDialog`, because it will center the text

![image](https://github.com/asjqkkkk/markdown_widget/assets/30992818/270a57eb-1609-4614-b134-37a9f2d8e75e)

```
CupertinoAlertDialog(
          content: SingleChildScrollView(
            child: Text(checkText),
          ),
        )
```
![image](https://github.com/asjqkkkk/markdown_widget/assets/30992818/6ea975bc-35c4-400e-83df-8d8ff122cdea)

**Comment by asjqkkkk** [comment]
@Time2HackJS I found a way to solve this issue, just need to set the `TextAlign` to the rich text, wait me to fix it

**Comment by Time2HackJS** [comment]
> @Time2HackJS I found a way to solve this issue, just need to set the `TextAlign` to the rich text, wait me to fix it

Any updates on this?

**Comment by asjqkkkk** [comment]
Hi @Time2HackJS , you can use `markdown_widget 2.3.2+3` like this:
```
...
MarkdownBlock(
          data: checkText,
          config: MarkdownConfig(configs: [...]),
          generator: MarkdownGenerator(richTextBuilder: (span) {
            return Text.rich(span, textAlign: TextAlign.start);
          }),
        )
...
```
<img width="320" alt="image" src="https://github.com/asjqkkkk/markdown_widget/assets/30992818/5c04c7ea-0d42-497a-8bb4-b25814935a9c">

**Comment by Time2HackJS** [comment]
@asjqkkkk thanks a lot!
