### ISSUE TITLE
添加图片目录属性

### ISSUE THREAD

**Issue by cxcel** [asjqkkkk/markdown_widget#151]
像flutter_markdown那样可以通过imageDirectory参数，控制markdown 图片所在目录。

像这样
      Markdown(
        data: markdownContent,

        imageDirectory: markdownPath,
      ),

**Comment by asjqkkkk** [comment]
@cxcel 你好，可以参考example中对`img` tag的实现，通过这样的方式，可以去自定义任意路径的图片

更加简单的方式是使用 `ImgConfig` 来统一处理所有的图片路径

**Comment by cxcel** [comment]
多谢
