### ISSUE TITLE
如何图片显示的圆角

### ISSUE THREAD

**Issue by OpenJarvisAI** [asjqkkkk/markdown_widget#153]
如何在config中设置啊

**Comment by asjqkkkk** [comment]
@OpenJarvisAI 你好，可以通过使用 `ImgConfig` 来进行图片Widget的自定义

**Comment by OpenJarvisAI** [comment]
@asjqkkkk  I configed but the clikc image view functio nare gone,

How to keep the click view and set broder readius?

I always think it could be better design keep theme seperately to config for uers.

**Comment by asjqkkkk** [comment]
@OpenJarvisAI 请参考 https://github.com/asjqkkkk/markdown_widget/blob/master/lib/widget/inlines/img.dart 中的实现
