### ISSUE TITLE
P blocks don't have dark mode by default

### ISSUE THREAD

**Issue by stefanosiano** [asjqkkkk/markdown_widget#154]
**Describe the bug**
P blocks don't have dark mode by default.
It seems the error lies in [this line](https://github.com/asjqkkkk/markdown_widget/blob/master/lib/widget/blocks/leaf/paragraph.dart#L34C38-L34C38), as it's the only config where `darkConfig` doesn't overwrite the color.

**To Reproduce**
Just put any text enabling the dark config, and the text will still be black.

**Expected behavior**
The text should be white.

Nice work with this library!

**Comment by asjqkkkk** [comment]
Hi @stefanosiano thanks for your issue, the current color of the text is controlled by the `Theme`, so there is no inclusion of color in `PConfig`. In the future, there may be consideration to remove darkConfig from `PConfig ` or include color in darkConfig.

**Comment by stefanosiano** [comment]
oh, I see.
I have to make some other test, as it was showing a dark text when using a dark theme (it was inside a Theme widget) with default values. I'll let you know if there is any news

**Comment by stefanosiano** [comment]
I can confirm it was an issue on how i created the Theme. I had to specify the text color, too, using 
```
              Theme(
                data: theme,
                child: DefaultTextStyle.merge(
                  style: TextStyle(color: theme.textTheme.bodyMedium!.color),
                  child: MarkdownBlock (...),
                ),
              )
```

**Comment by henry2man** [comment]
@asjqkkkk I think this is still an issue. AFAIK This only affects to `PConfig.darkConfig` because any other configs have proper `color: Colors.white` (or gray ones).

@stefanosiano it was a legitimate issue still today present in `markdown_widget: ^2.3.2+8` 

https://github.com/asjqkkkk/markdown_widget/blob/master/lib/widget/blocks/leaf/paragraph.dart#L34C38-L34C38
