### ISSUE TITLE
[Bug] Tab (\t) being replaced with new line (\n) in Pre element

### ISSUE THREAD

**Issue by PeronGH** [asjqkkkk/markdown_widget#159]
**Describe the bug**
Tab (\t) being replaced with new line (\n) in pre element.

**To Reproduce**
1. Set up wrapper for PreConfig, like this:
```dart
PreConfig(wrapper: (child, code, language) {
    print(json.encode(code));
    return // ...
})
```

2. Try rendering code block including tab:
```go
package main

import "fmt"

func main() {
	fmt.Println("Hello, World!")
}
```

3. It prints `"package main\n\nimport \"fmt\"\n\nfunc main() {\n\nfmt.Println(\"Hello, World!\")\n}\n"`.

**Expected behavior**
Tab should still be tab.

**Environment:**
```
• Flutter version 3.16.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.13.6/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision b0366e0a3f (9 weeks ago), 2023-12-05 19:46:39 -0800
• Engine revision 54a7145303
• Dart version 3.2.3
• DevTools version 2.28.4
• markdown_widget: 2.3.2+3
```

**Platform**
Web

**Comment by asjqkkkk** [comment]
This issue has been fixed by `v2.3.2+4`
