### ISSUE TITLE
把例子copy到项目里，报错

### ISSUE THREAD

**Issue by alun1** [asjqkkkk/markdown_widget#16]
E/flutter ( 9129): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a closure - Function 'buildMarkdownGenerator':.)
E/flutter ( 9129): #0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:551:55)
E/flutter ( 9129): #1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:391:7)
E/flutter ( 9129): #2      compute (package:flutter/src/foundation/_isolates_io.dart:23:41)
E/flutter ( 9129): #3      _MarkdownWidgetState.initialState (package:markdown_widget/markdown_widget.dart:70:12)
E/flutter ( 9129): #4      _MarkdownWidgetState.initState (package:markdown_widget/markdown_widget.dart:56:5)
E/flutter ( 9129): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter ( 9129): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 9129): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9129): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9129): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 9129): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9129): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9129): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 9129): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 9129): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 9129): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 9129): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9129): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9129): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 9129): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 9129): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 9129): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 9129): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9129): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9129): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 9129): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 9129): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 9129): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 9129): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9129): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9129): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 9129): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 9129): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 9129): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 9129): #34     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4617:11)
E/flutter ( 9129): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9129): #36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
E/flutter ( 9129): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9129): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9129): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 9129): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 9129): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 9129): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter ( 9129): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 9129): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9129): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:

**Comment by asjqkkkk** [comment]
有没有具体的使用代码？只看这个报错信息无法定位问题

**Comment by asjqkkkk** [comment]
v1.1.4应该解决了这个问题，可以升级试一下
