### ISSUE TITLE
[Question] How to get the maximum height required by the rendered widget.

### ISSUE THREAD

**Issue by nrbnlulu** [asjqkkkk/markdown_widget#161]
Is there a way to know the maximum height of the rendered widget? 
Sorry if it is a dumb question I'm a flutter noob.

**Comment by asjqkkkk** [comment]
Hi @nrbnlulu , this issue is unrelated to this package. You should ask Google instead. Otherwise, all I can do is help you ask Google, which seems odd 

https://stackoverflow.com/questions/49307677/how-can-i-get-the-height-of-a-widget

**Comment by nrbnlulu** [comment]
You are probably right. Though if I may ask an help from you it would be nice.
I am trying to implement a text box similar to what the very textbox here on github.
If you pass long text the box would render long enough to show it all **without scrolling** is that possible with your widget?
This is what I have currently
![image](https://github.com/asjqkkkk/markdown_widget/assets/88795475/c9fa19b9-6d3d-4baf-9db7-4e78b7a14326)
And this is how I **want** it to look like
![image](https://github.com/asjqkkkk/markdown_widget/assets/88795475/c7c65312-ba8b-409c-965f-d1b96ac2363e)

leaving aside that my implementation looks ugly :upside_down_face: I just want to be able to see **both** of the cats **without** the inner scroller.
