### ISSUE TITLE
Add a "copy to clipboard" for code like chatgpt

### ISSUE THREAD

**Issue by sharan21** [asjqkkkk/markdown_widget#162]
**Is your feature request related to a problem? Please describe.**
There is no automatic code copy support

**Describe the solution you'd like**
Whenever there is an opening and closing three consecutive backticks like ```this```, the widget can create a copy to clipboard widget.

**Describe alternatives you've considered**
Cannot think of any.

**Additional context**
Refer to how it looks for chatgpt, can we do something similar here?

**Comment by sharan21** [comment]
I think this feature is already there? Can you please provide an example for how this can be done?

**Comment by sharan21** [comment]
this is my code: 
```
 Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: MarkdownGenerator().buildWidgets(
                        config: MarkdownConfig.darkConfig,
                        message.message,
                      ),
                    ),
                  ```

**Comment by asjqkkkk** [comment]
Hi @sharan21 , you can visit the online demo :  https://asjqkkkk.github.io/markdown_widget/ 

there is already the `copy button` for code block

and the code is here

https://github.com/asjqkkkk/markdown_widget/blob/master/example/lib/widget/code_wrapper.dart
