### ISSUE TITLE
Code block copy and paste button

### ISSUE THREAD

**Issue by kaonick** [asjqkkkk/markdown_widget#165]
It is hoped that the copying and pasting of code blocks can be added

**Comment by asjqkkkk** [comment]
Hi @kaonick  , you can visit the online demo : https://asjqkkkk.github.io/markdown_widget/

there is already the copy button for code block

and the code is here

https://github.com/asjqkkkk/markdown_widget/blob/master/example/lib/widget/code_wrapper.dart
