### ISSUE TITLE
Support for "mermaid"

### ISSUE THREAD

**Issue by S4tyendra** [asjqkkkk/markdown_widget#168]
**Problem:**
There's currently no support for Mermaid diagrams in the markdown widget.

**Solution:**
I would like the markdown widget to have built-in support for Mermaid diagrams, allowing users to easily create and display diagrams within their markdown content.

**Additional Context:**
Mermaid is a markdown-like language used for generating diagrams and flowcharts directly from text descriptions. It allows users to create various types of diagrams, including flowcharts, sequence diagrams, Gantt charts, and more, using a simple and intuitive syntax. Mermaid diagrams can be easily integrated into markdown documents, wikis, presentations, and other platforms that support Markdown. It's widely used by developers, technical writers, and others to create visual representations of processes, systems, and data flows.

**links:**

test it here: https://mermaid.live/edit
syntax: https://emersonbottero.github.io/mermaid-docs/syntax/classDiagram.html
gh links: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams
https://handbook.gitlab.com/handbook/tools-and-tips/mermaid/
pub.dev :  https://pub.dev/packages/mermaid

**Comment by zilanfeng** [comment]
When is **mermaid** supported～

**Comment by asjqkkkk** [comment]
now you can refer to the code at https://github.com/asjqkkkk/markdown_widget/blob/main/example/lib/markdown_custom/mermaid.dart to implement the mermaid support
