### ISSUE TITLE
Code Bloc - Question

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#17]
The web version of flutter doesn't support text selection very well. So i wanna to add button to copy code(like in screenshot) here.
![image](https://user-images.githubusercontent.com/44783405/81466865-6fefae00-91dd-11ea-9b84-322b7c2edffd.png)
https://dartpad.dev/embed-dart.html?theme=dark

**Comment by asjqkkkk** [comment]
now v1.1.5 add `PreWrapper` in `PreConfig`, you can custom your copy button by it

**Comment by asjqkkkk** [comment]
now update to v1.1.6, and use it like this:
```
preConfig: PreConfig(preWrapper: (preWidget, text) {
            return Stack(
              children: <Widget>[
                Center(child: preWidget),
                Align(
                  alignment: Alignment.topRight,
                  child: YourCopyButton(),
                )
              ],
            );
          }),
```

**Comment by mrpvb-pvbk** [comment]
How copy text of this bloc?

**Comment by mrpvb-pvbk** [comment]
Background animation of IconButton works not very well. Shadow behind the code block.
![Screenshot (2)](https://user-images.githubusercontent.com/44783405/81493480-5451d980-92a9-11ea-9b33-25f4ab5814e8.png)
![Screenshot (3)](https://user-images.githubusercontent.com/44783405/81493484-56b43380-92a9-11ea-9d3c-5315180a29d6.png)
![Screenshot (34)](https://user-images.githubusercontent.com/44783405/81493486-59168d80-92a9-11ea-9aea-a86e228efe77.png)

Im using Flutter Web and this code:
```
MarkdownGenerator(
                    data: snapshot.data,
                    childMargin: EdgeInsets.all(10.0),
                    styleConfig: StyleConfig(
                      pConfig: PConfig(selectable: true),
                      preConfig: PreConfig(preWrapper: (preWidget, text) {
                        return Stack(
                          children: <Widget>[
                            preWidget,
                            Align(
                              alignment: Alignment.topRight,
                              child: IconButton(
                                  icon: Icon(Icons.content_copy),
                                  onPressed: () {
                                    Clipboard.setData(
                                        new ClipboardData(text: text));
                                    Scaffold.of(context).showSnackBar(SnackBar(
                                        content: Text('Код скопирован')));
                                  }),
                            )
                          ],
                        );
                      }),
                    )
```

**Comment by asjqkkkk** [comment]
> Background animation of IconButton works not very well. Shadow behind the code block.
> ![Screenshot (2)](https://user-images.githubusercontent.com/44783405/81493480-5451d980-92a9-11ea-9b33-25f4ab5814e8.png)
> ![Screenshot (3)](https://user-images.githubusercontent.com/44783405/81493484-56b43380-92a9-11ea-9d3c-5315180a29d6.png)
> ![Screenshot (34)](https://user-images.githubusercontent.com/44783405/81493486-59168d80-92a9-11ea-9aea-a86e228efe77.png)
> 
> Im using Flutter Web and this code:
> 
> ```
> MarkdownGenerator(
>                     data: snapshot.data,
>                     childMargin: EdgeInsets.all(10.0),
>                     styleConfig: StyleConfig(
>                       pConfig: PConfig(selectable: true),
>                       preConfig: PreConfig(preWrapper: (preWidget, text) {
>                         return Stack(
>                           children: <Widget>[
>                             preWidget,
>                             Align(
>                               alignment: Alignment.topRight,
>                               child: IconButton(
>                                   icon: Icon(Icons.content_copy),
>                                   onPressed: () {
>                                     Clipboard.setData(
>                                         new ClipboardData(text: text));
>                                     Scaffold.of(context).showSnackBar(SnackBar(
>                                         content: Text('Код скопирован')));
>                                   }),
>                             )
>                           ],
>                         );
>                       }),
>                     )
> ```

It seems like not `MarkdownWidget` 's problem

**Comment by mrpvb-pvbk** [comment]
#Offtop
How can I read md files from local folder using Flutter web?

**Comment by asjqkkkk** [comment]
> #Offtop
> How can I read md files from local folder using Flutter web?

you shuold search the answers by google😅

**Comment by mrpvb-pvbk** [comment]
> > #Offtop
> > How can I read md files from local folder using Flutter web?
> 
> you shuold search the answers by google😅

I didnt find an answer😓

**Comment by asjqkkkk** [comment]
> > > #Offtop
> > > How can I read md files from local folder using Flutter web?
> > 
> > 
> > you shuold search the answers by google😅
> 
> I didnt find an answer😓

It's the same as mobile

**Comment by mrpvb-pvbk** [comment]
> > > > #Offtop
> > > > How can I read md files from local folder using Flutter web?
> > > 
> > > 
> > > you shuold search the answers by google😅
> > 
> > I didnt find an answer😓
> 
> It's the same as mobile

Without assets. I'm will add more files and folder but it takes a long time to add everything to pubspec. yaml and use for rootBundle.

**Comment by asjqkkkk** [comment]
It is not necessary to declare all the file directories, just declare the root path of files

**Comment by mrpvb-pvbk** [comment]
How to solve it?
![Screenshot (4)](https://user-images.githubusercontent.com/44783405/81498885-28961a00-92d0-11ea-8f6d-6c5877bde195.png)
