### ISSUE TITLE
Syntax Highlighter add a parameter for all languages

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#18]
**Is your feature request related to a problem? Please describe.**
Yes. I need to change the config for each language.

**Describe the solution you'd like**
```
 Widget buildMarkdown() => MarkdownWidget(
        data: data,
        styleConfig: StyleConfig(
          preConfig: PreConfig(
            language: 'all', //here
            theme: theme.a11yLightTheme
          )
        ),
      );
```

**Additional context**
You can reduce the support for highlighted words, but the main thing is that it affects most languages.

**Comment by asjqkkkk** [comment]
in v1.1.5 language can be automatically detected if you pass the **null** 'language'
