### ISSUE TITLE
请教手机端如何识别网址，并改变字体

### ISSUE THREAD

**Issue by zilanfeng** [asjqkkkk/markdown_widget#180]
我需要识别markdown中的普通网址，并改变字体，类似：www.baidu.com，需要改变颜色和增加下划线。我尝试适用LinkConfig，好像并没有作用。

**Comment by asjqkkkk** [comment]
@zilanfeng 你好，类似【www.baidu.com】是可以被识别成网址的，都是它需要避免与其他字符连在一起，中间需要用空格分开

比如这样【 www.baidu.com 】

![image](https://github.com/asjqkkkk/markdown_widget/assets/30992818/69c7dbd3-839a-4a89-a1b9-81c46d8a1633)
