### ISSUE TITLE
在网址换行时有UI布局异常现象

### ISSUE THREAD

**Issue by LiuYimin** [asjqkkkk/markdown_widget#181]
<img width="270" alt="截屏2024-07-30 10 23 32" src="https://github.com/user-attachments/assets/1cd9ead9-79bb-44be-ae09-6cd958fa897e">
如图，换行后，右边部分还是空着的，而且是链接可点区域

**Comment by asjqkkkk** [comment]
@LiuYimin 你好，这是文本所在区域的宽度不够，导致它换行了，属于正常现象

![image](https://github.com/user-attachments/assets/3b9911d5-7493-41fd-a0c7-c5000c1c85c2)

比如图中出现的情况，或者下面这种大段英文被识别成同一单词，也会有这种情况
![image](https://github.com/user-attachments/assets/0f04f4a6-f6c6-41cf-9c21-d7de35657e44)
