### ISSUE TITLE
Can't find styleConfig attribute of MarkdownWidget

### ISSUE THREAD

**Issue by cryindevil** [asjqkkkk/markdown_widget#182]
I like your package! However I am experimenting with some advanced feature and like to ask : I saw " styleConfig "attribute of MarkdownWidget mentioned in previous issues but I can't find it in 2.0.0 version. I guess is it changed into another attribute?
Also, I'd like to ask MarkdownWidget it a superset of MarkdownBody class, can it accomplish all tasks which MarkdownBody can?

**Comment by asjqkkkk** [comment]
Hi @cryindevil , MarkdownWidget it the superset of MarkdownBody. 

After v2.0.0， you need use `MarkdownConfig` to custom your configs

**Comment by cryindevil** [comment]
So for example, may I ask if I want to use the _imageBuilder_ attribute in the MarkdownBody, how can I use it in the MarkdownWidget? Since I didn't see the corresponding attribute in the MarkdownWidget. Thanks @asjqkkkk
