### ISSUE TITLE
如何注入flutter Widget

### ISSUE THREAD

**Issue by MR-MaoJiu** [asjqkkkk/markdown_widget#183]
大佬们，我有一个需求需要正则匹配出特殊定的字符然后使用flutter Widget进行渲染填充请问我该怎么使用？

**Comment by asjqkkkk** [comment]
@MR-MaoJiu 你好，可以参考 https://github.com/asjqkkkk/markdown_widget/blob/master/example/lib/markdown_custom/latex.dart
的实现
