### ISSUE TITLE
Items for long lists are not aligned.

### ISSUE THREAD

**Issue by danielporto** [asjqkkkk/markdown_widget#19]
**Describe the bug**
List comprised of more than 9 items are not aligned. The text for items from 10 and beyond is shifted. It would be better if all text have the same margins or an option to define it.
Problem should repeat for longer lists when the number of characters changes (100, 1000,...) 

**To Reproduce**
Create any numbered list with more than 10 items.

**Expected behavior**
Text of all elements in list are aligned.

**Screenshots**

**Environment(please complete the following information):**
Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G4032, locale en-PT)
    • Flutter version 1.17.0 at /usr/local/Caskroom/flutter/latest/flutter
    • Framework revision e6b34c2b5c (8 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

**Comment by asjqkkkk** [comment]
Could you provide a specific screenshot or source data?

And is it used on the web or on Mobile？

**Comment by danielporto** [comment]
Mobile, here goes the screenshot. 
Please also notice the unintended line break after a bold text. 
It seems to happen in long texts. The first one marked bold works, the second in the same line breaks the line. 

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-10 at 12 11 19](https://user-images.githubusercontent.com/1652891/81497621-879b6500-92b7-11ea-97a5-379d18800e5b.png)

**Comment by asjqkkkk** [comment]
It seems that it should be the positioning problem of WidgetSpan in RichText

I will consider later to see if there is a suitable solution

**Comment by asjqkkkk** [comment]
Hi, set `selectable` in `PConfig` to **false** can solve this issue.
But if you do that, you can no longer select text, because of #2

**Comment by danielporto** [comment]
nice, it did solve the issue with the breaks after bold text.
I've enabled. No need to select.
The shift remains though.

**Comment by asjqkkkk** [comment]
> nice, it did solve the issue with the breaks after bold text.
> I've enabled. No need to select.
> The shift remains though.

My English is not very good， dose it mean the problem is solved?

**Comment by danielporto** [comment]
Sorry.
Problem 1 is solved: line breaks after bold text
Problem 2 is not: the paragraph shift starting with number 10, 11, 12... like in the screenshot.

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/81700421-364bcb00-949b-11ea-804e-a3d2399b3984.png)

do you mean this ?

**Comment by danielporto** [comment]
Yes, exactly. 
That's not horrible but would be nice to have it aligned.

**Comment by asjqkkkk** [comment]
you can use `OlConfig` with `IndexWidget` to custom the index, that can solve this problem

such as this:

```
        styleConfig: StyleConfig(
          olConfig: OlConfig(
            indexWidget: (deep, index){
              return Container(
                margin: EdgeInsets.only(left: 5, right: 5),
                child: Text(
                  index < 10 ?' $index.' : '$index',
                ),
              );
            }
          ),)
```

**Comment by danielporto** [comment]
Nice! it worked!
