### ISSUE TITLE
手机端显示表格时，超出屏幕的部分无法滑动

### ISSUE THREAD

**Issue by RubinTry** [asjqkkkk/markdown_widget#192]
![1c1a232aa94fea98fd7468800d18652](https://github.com/user-attachments/assets/5bba4d99-dc84-4070-a737-2b7f50b8469c)
ruti如题，超出屏幕部分无法滑动

**Comment by asjqkkkk** [comment]
可以对 `TableConfig`的 `WidgetWrapper`添加SingleChildScrollView配置，默认的Table是全屏占用不支持横向滑动的
