### ISSUE TITLE
生成的Toc点击没有跳转效果

### ISSUE THREAD

**Issue by acmenlei** [asjqkkkk/markdown_widget#193]
作者您好，使用该库过程中遇到点击没有跳转到对应heading节点的效果，不太清楚是未实现还是我的使用方式有问题呢？麻烦看一下，非常感谢！🙏

【依赖版本】
<img width="220" alt="image" src="https://github.com/user-attachments/assets/92b3e6fd-cd3e-4960-bc01-5f73a4a31a82">

【使用效果如下】：

https://github.com/user-attachments/assets/6a4dfc0c-68d7-452b-8b47-5fc48790bd8c

【使用方式如下】：

根文件：
<img width="577" alt="image" src="https://github.com/user-attachments/assets/59a37838-ce02-42f1-bf56-6ce44d8f15cc">

md_view.dart：
<img width="600" alt="image" src="https://github.com/user-attachments/assets/02c8ba03-ad65-4208-ba7d-de7c3051e2f4">

bottom_info_action.dart
<img width="690" alt="image" src="https://github.com/user-attachments/assets/6047412a-e780-44ec-9e7d-b9df9fefd88a">

**Comment by asjqkkkk** [comment]
@acmenlei 你好，不建议在 `build` 方法中生成新的 `TocController` 进行传值，`TocController`的使用方式可以参考`TextFormField`的`TextEditingController`，它应该在一个具有状态保存功能的区域里面生成与销毁，比如StatefulWidget
