### ISSUE TITLE
Selectable text not working

### ISSUE THREAD

**Issue by TheBestMoshe** [asjqkkkk/markdown_widget#2]
When I dig into the code, it seems like the text is set to be selectable by default, however, the generated code is just `RichText` widget and not a `SelectableText.rich` widget.

Can we get proper support for selectable text, and as a bonus, if we can pass in `toolbarOptions` that would be even better.

**Comment by asjqkkkk** [comment]
Hi,
`SelectableText.rich` only supports `TextSpan`， but some tag widgets are made up of `WidgetSpan`， So I can only use `SelectableText`

Now v1.0.8 supports whether to enable `selectable` in `PConfig` 😄

**Comment by TheBestMoshe** [comment]
> Now v1.0.8 supports whether to enable `selectable` in `PConfig`

Thanks! This fits my primary use case.

> SelectableText.rich only supports `TextSpan`， but some tag widgets are made up of `WidgetSpan`， So I can only use `SelectableText`

Is this why selections can't go between `strong` (bold) and regular text within the `<p>` tags?

**Comment by asjqkkkk** [comment]
> Is this why selections can't go between `strong` (bold) and regular text within the `<p>` tags?

yes, if `SelectableText.rich` supports `WidgetSpan` ，this issue will be solved

**Comment by Shreedhar73** [comment]
@asjqkkkk 
Hey, amazing package thanks.

I am facing a problem ( it might be expected behaviour ).
 Initially ,I selected multi lines of text with different tags( headings, lists) and copy the selected text.
When i pasted the text else where, the formatting is not being maintained. 

Can you please look in to this?

**Comment by asjqkkkk** [comment]
Hi @Shreedhar73 , currently, the `markdown_widget` utilizes `SelectionArea` to implement the copy function. Indeed, it has the issue you mentioned. It may be necessary to explore whether there can be extensions in this regard in the future to see how to achieve the effect you described.
At the same time, you can also keep an eye on this issue: https://github.com/flutter/flutter/issues/104548

**Comment by Shreedhar73** [comment]
@asjqkkkk Thanks
