### ISSUE TITLE
Text alignment control

### ISSUE THREAD

**Issue by danielporto** [asjqkkkk/markdown_widget#21]
**Is your feature request related to a problem? Please describe.**
The text rendered is aligned to left only. 

**Describe the solution you'd like**
It would be nice if we could justify, centralize and align it to right.

**Describe alternatives you've considered**
unfortunately there is no alternative right now.

**Comment by asjqkkkk** [comment]
do you mean `TextAlign` property ?
![image](https://user-images.githubusercontent.com/30992818/81710778-a2cbc780-94a5-11ea-8d80-a4bbc660997f.png)

**Comment by danielporto** [comment]
Yep; 
How can access this property from PConfig (I imagine this is the object, I'm starting to understand...)

**Comment by danielporto** [comment]
Any hint on how access this property for a regular text?

**Comment by asjqkkkk** [comment]
😂I haven't provided this function yet
I will try to introduce it in v1.2.0

**Comment by miniskulljob** [comment]
Really looking forward to this being implemented.

**Comment by asjqkkkk** [comment]
> Really looking forward to this being implemented.

sorry, I'm busy finding a new job now, I'll try to solve this issue today😅

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/82887415-8b4b0f00-9f7a-11ea-9786-d1f0a72a8160.png)

Is that mean `TextDirection` ?

just like this:https://gallery.flutter.dev/#/

![image](https://user-images.githubusercontent.com/30992818/82887573-cbaa8d00-9f7a-11ea-9e29-cd6857290bb3.png)

![image](https://user-images.githubusercontent.com/30992818/82887591-d2390480-9f7a-11ea-9cdf-86fd3993ed6e.png)

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/82889554-7f148100-9f7d-11ea-9388-5d62d0598bbb.png)

![image](https://user-images.githubusercontent.com/30992818/82889614-96536e80-9f7d-11ea-9156-aab895cbf6e1.png)

Is that ok?

**Comment by miniskulljob** [comment]
No, that's RTL support that another user mentioned in this issue: [#14](https://github.com/asjqkkkk/markdown_widget/issues/14)

What we mean is `TextAlignment`. You mentioned it in this comment: https://github.com/asjqkkkk/markdown_widget/issues/21#issuecomment-627406105

**Comment by asjqkkkk** [comment]
> No, that's RTL support that another user mentioned in this issue: [#14](https://github.com/asjqkkkk/markdown_widget/issues/14)
> 
> What we mean is `TextAlignment`. You mentioned it in this comment: [#21 (comment)](https://github.com/asjqkkkk/markdown_widget/issues/21#issuecomment-627406105)

Hi, you can have a try for:
```
  markdown_widget:
    git:
      url: https://github.com/asjqkkkk/markdown_widget.git
      ref: dev
```

and you can use `TextConfig` to set `TextAlign`, and it obly supports for mobile, if there seems to be no problem, I will update to v1.2.0😄

**Comment by miniskulljob** [comment]
> > No, that's RTL support that another user mentioned in this issue: [#14](https://github.com/asjqkkkk/markdown_widget/issues/14)
> > What we mean is `TextAlignment`. You mentioned it in this comment: [#21 (comment)](https://github.com/asjqkkkk/markdown_widget/issues/21#issuecomment-627406105)
> 
> Hi, you can have a try for:
> 
> ```
>   markdown_widget:
>     git:
>       url: https://github.com/asjqkkkk/markdown_widget.git
>       ref: dev
> ```
> 
> and you can use `TextConfig` to set `TextAlign`, and it only supports for mobile now, if there seems to be no problem, I will update to v1.2.0😄

It's working, but it only centers the first line of the text, the next lines are always left aligned.

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/82899433-8e9bc600-9f8d-11ea-9123-7920e8383c6b.png)

Is this right?

**Comment by miniskulljob** [comment]
Yes, that's how it should work.

**Comment by asjqkkkk** [comment]
> Yes, that's how it should work.

can you show your screenshot, and the code , and your environment to help me locate the problem?

**Comment by miniskulljob** [comment]
```
Padding(
  padding: const EdgeInsets.all(20.0),
  child: MarkdownWidget(
    data: '''
**Lorem ipsum dolor**

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis sollicitudin ante. Aenean nisi sapien, sodales eu massa quis, eleifend aliquet eros.

Duis molestie auctor arcu, et euismod sapien efficitur id. Nam semper gravida nunc vitae venenatis. Proin quis accumsan quam. Sed auctor vehicula diam et lobortis. Proin vitae sodales sapien.

Fusce vitae urna ac nulla finibus convallis sed sit amet velit. Quisque non odio eget diam volutpat ullamcorper at at lorem. Etiam viverra erat vel sem elementum consequat quis pulvinar massa. Pellentesque lacus dolor, posuere eu congue vel, aliquam eu augue.
''',
    styleConfig: StyleConfig(
    pConfig: PConfig(
      textConfig: TextConfig(textAlign: TextAlign.center)
    )
  ),
),
```

![image](https://user-images.githubusercontent.com/1895917/82903812-d147a900-9f61-11ea-9a49-429fd285ecdb.png)


```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [VersiÃ³n 10.0.18363.778], locale es-ES)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by asjqkkkk** [comment]
> ```
> Padding(
>   padding: const EdgeInsets.all(20.0),
>   child: MarkdownWidget(
>     data: '''
> **Lorem ipsum dolor**
> 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis sollicitudin ante. Aenean nisi sapien, sodales eu massa quis, eleifend aliquet eros.
> 
> Duis molestie auctor arcu, et euismod sapien efficitur id. Nam semper gravida nunc vitae venenatis. Proin quis accumsan quam. Sed auctor vehicula diam et lobortis. Proin vitae sodales sapien.
> 
> Fusce vitae urna ac nulla finibus convallis sed sit amet velit. Quisque non odio eget diam volutpat ullamcorper at at lorem. Etiam viverra erat vel sem elementum consequat quis pulvinar massa. Pellentesque lacus dolor, posuere eu congue vel, aliquam eu augue.
> ''',
>     styleConfig: StyleConfig(
>     pConfig: PConfig(
>       textConfig: TextConfig(textAlign: TextAlign.center)
>     )
>   ),
> ),
> ```
> 
> ![image](https://user-images.githubusercontent.com/1895917/82903812-d147a900-9f61-11ea-9a49-429fd285ecdb.png)
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [VersiÃ³n 10.0.18363.778], locale es-ES)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [√] Android Studio (version 3.6)
> [√] VS Code (version 1.45.1)
> [√] Connected device (1 available)
> 
> • No issues found!
> ```

I konw the problem. set `selectable` to **false**, and then it will be ok

**Comment by miniskulljob** [comment]
Yep, setting `selectable` to `false` certainly works. Nice catch.
Thanks for the help, good work.

**Comment by asjqkkkk** [comment]
> Yep, setting `selectable` to `false` certainly works. Nice catch.
> Thanks for the help, good work.

Hi, you can change your dependency to v1.2.0 now

**Comment by danielporto** [comment]
Man it works great!
Thanks a lot!.
