### ISSUE TITLE
TocController get current position(pixels)

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#23]
**Is your feature request related to a problem? Please describe.**
Yes. TocController supports the scrollTo and jumpTo methods. But it doesn't allow you to get the pixel value to use.

**Describe the solution you'd like**
```
 @override
  void initState() {
    _tocController = new TocController(
      initialScrollOffset:
          _position != widget.position ? 0.0 : widget.scrollPosition
    )..addListener(() {
        _scrollPosition = _tocController.position.pixels.roundToDouble();
      });
    super.initState();
  }
```

**Comment by asjqkkkk** [comment]
`MarkdownWidget` is based on `ScrollablePositionedList` beacause of **TOC function**

It doesn't provide the ability to get pixels, so if you wan to get `pixels`, please use `ListView` and `MarkdownGenerator` with `ScrollController`

**Comment by mrpvb-pvbk** [comment]
I want to use TocListWidget too😷

**Comment by asjqkkkk** [comment]
> I want to use TocListWidget too😷

this hard to do, because `ScrollablePositionedList` dosen't support it. 

you can submit a feature request to [ScrollablePositionedList](https://github.com/google/flutter.widgets/issues) 😂

**Comment by mrpvb-pvbk** [comment]
Ok
