### ISSUE TITLE
Incorrect rendering in tables

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#25]
**Describe the bug**
Look at this code:
![image](https://user-images.githubusercontent.com/44783405/82687336-d7870e00-9c5f-11ea-8e6a-4e7aa2227995.png)
What it looks like in GitHub the Markdown rendering:
![image](https://user-images.githubusercontent.com/44783405/82687576-22a12100-9c60-11ea-9f8c-cdba19901533.png)
And widget rendering:
![image](https://user-images.githubusercontent.com/44783405/82687734-5aa86400-9c60-11ea-9021-62ed36dd2338.png)
---
So bug here:
![image](https://user-images.githubusercontent.com/44783405/82687912-a22ef000-9c60-11ea-872f-09f5cdfea4da.png)
The gap between '||' and 'b' has disappeared.

**Platform**
Does the problem appear on the **Web** or on the **Mobile**？
I saw it on a web platform.

**Comment by asjqkkkk** [comment]
Yes, it seems to be a wrong parse, I'm checking where the problem is

**Comment by asjqkkkk** [comment]
It may be `markdown` package not parse data correctly
I have submitted a [issue](https://github.com/dart-lang/markdown/issues/287)
