### ISSUE TITLE
Improving table rendering

### ISSUE THREAD

**Issue by the-thirteenth-fox** [asjqkkkk/markdown_widget#26]
1. If the table is wide add horizontal scrolling support.
![Screenshot_20200514-221350_GitHub](https://user-images.githubusercontent.com/44783405/82694665-55e9ad00-9c6c-11ea-8308-375d33784e0b.jpg)
![Screenshot_20200514-221356_GitHub](https://user-images.githubusercontent.com/44783405/82694671-584c0700-9c6c-11ea-9a01-988d9383443d.jpg)
`this.supportVerticalScrolling = true;`
2. **Bold** text in titles if it needed.
![image](https://user-images.githubusercontent.com/44783405/82695048-00fa6680-9c6d-11ea-85d6-d3aacb8290e4.png)
3. Column compression.
![image](https://user-images.githubusercontent.com/44783405/82695397-af061080-9c6d-11ea-82cb-7e6ca8868d61.png)
How it should be
![image](https://user-images.githubusercontent.com/44783405/82695446-c6dd9480-9c6d-11ea-8298-d6edba165c1a.png)

**Comment by asjqkkkk** [comment]
use `TableConfig` with `wrapBuilder` to wrap `Table` into a `SingleChildScrollView` can resolve your first problem

**Comment by asjqkkkk** [comment]
use `TableConfig` with `headerStyle` can resolve your second problem

**Comment by asjqkkkk** [comment]
the third problem has not yet a better solution

**Comment by mrpvb-pvbk** [comment]
Can u provide example for scrolling in table?

It is not working for my tables:
```
 tableConfig: TableConfig(
                                  wrapBuilder: (table) => SingleChildScrollView(
                                    scrollDirection: Axis.vertical,
                                    child: table,
                                  ),
```

**Comment by bravekingzhang** [comment]
@asjqkkkk I have the same problem when I render markdown table in Listview

![image](https://user-images.githubusercontent.com/4476322/232686883-3a8ff086-b64a-4166-a102-2837cdebc846.png)

it seems that the table is overflow of the boundary，could you help me solve this problem ,thank you 。

**Comment by bravekingzhang** [comment]
@asjqkkkk I have solve this problem , this is a nice libaray

```dart
return SelectionArea(
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: MarkdownGenerator(
              config: config.copy(configs: [
                isDark
                    ? PreConfig.darkConfig.copy(wrapper: codeWrapper)
                    : const PreConfig().copy(wrapper: codeWrapper),
                TableConfig(
                  wrapper: (table) => SingleChildScrollView(
                    scrollDirection: Axis.horizontal,// 可横向滑动
                    child: table,
                  ),
                  headerStyle: const TextStyle(fontWeight: FontWeight.bold),
                ),
              ]),
            ).buildWidgets(text)),
      ),
    );
```

**Comment by asjqkkkk** [comment]
This issue is too old, if necessary, please create an new issue
