### ISSUE TITLE
[Question] Custom ScrollController with Toc

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#27]
I need to use my ScrollController and I still want to add Toc support😥. how can I implement this? Preferably with an example.

**Comment by asjqkkkk** [comment]
`Toc` function is based on `ScrollablePositionedList` , if you want to use `TOC` , just use `TocController` .

but if you want your own `ScrollController` with `TOC`, I think it's very hard to achieve.
you can also use `MarkdownGenerator` to  achieve your own `MarkdownWidget`, so you can do what you want to do

**Comment by mrpvb-pvbk** [comment]
What if add the current position checker to the TOC controller?

**Comment by asjqkkkk** [comment]
> What if add the current position checker to the TOC controller?

![image](https://user-images.githubusercontent.com/30992818/86200840-6147c680-bb90-11ea-8fb7-d7ff68e1f233.png)

`currentToc` will be public in v1.2.2, so you can get current position by it

**Comment by mrpvb-pvbk** [comment]
I tried to use this construction:
```
    _tocController = new TocController()
      ..addListener(() {
        _indexToc = _tocController.currentToc.index;
      });
```
to get the index of current widget, but it is updated when the TOC header changes.

**Comment by asjqkkkk** [comment]
> I tried to use this construction:
> 
> ```
>     _tocController = new TocController()
>       ..addListener(() {
>         _indexToc = _tocController.currentToc.index;
>       });
> ```
> 
> to get the index of current widget, but it is updated when the TOC header changes.

I think this is unnecessary, because `currentToc` is always updated by new one

**Comment by mrpvb-pvbk** [comment]
But if I have one header then how to get the index of the current widget.

**Comment by asjqkkkk** [comment]
> But if I have one header then how to get the index of the current widget?

What dose `one header` mean😂

**Comment by mrpvb-pvbk** [comment]
![image](https://user-images.githubusercontent.com/44783405/87133892-a363bd00-c2a0-11ea-8c72-2cf8972ef64f.png)
Like this. I wanna to know index of widget when scrolling down

**Comment by asjqkkkk** [comment]
You can refer to how I did it in the [example](https://github.com/asjqkkkk/markdown_widget/tree/master/example)

![image](https://user-images.githubusercontent.com/30992818/87134912-e4bd9200-c2cb-11ea-885a-95096bfe9239.png)

**Comment by mrpvb-pvbk** [comment]
There is no solution to my problem here. 

When i leave from page i wanna to save current position. And when i use like this: `_tocController.currentToc.index` in my example it always 0. The fact is that the text can be large and with a single title. So index can be updated by new one(

**Comment by asjqkkkk** [comment]
the index is followed by `Title` 
![image](https://user-images.githubusercontent.com/30992818/87135896-4cc0a800-c2cd-11ea-85c1-8c9c6c2dca99.png)

**Comment by asjqkkkk** [comment]
if there is only one title, the index will only be `0`

**Comment by mrpvb-pvbk** [comment]
> if there is only one title, the index will only be `0`

Ow. So it turns out I don't have the ability to get the current position with TOC controller? 0:

**Comment by asjqkkkk** [comment]
I don't understand what you want to get, maybe you mean `getTitleIndexWithWidgetIndex` in `TocController`?

**Comment by asjqkkkk** [comment]
you mean you want to get current index for all `widgets` or all `Titles`?

**Comment by mrpvb-pvbk** [comment]
> you mean you want to get current index for all `widgets` or all `Titles`?

all `widgets`

**Comment by asjqkkkk** [comment]
> > you mean you want to get current index for all `widgets` or all `Titles`?
> 
> all `widgets`

use this ,you can get current widget's index
![image](https://user-images.githubusercontent.com/30992818/87137861-23ede200-c2d0-11ea-8ffd-efc1300dfccc.png)

you can find it in example

**Comment by mrpvb-pvbk** [comment]
can u provide example how to use it?  I don't understand how to use this.

**Comment by asjqkkkk** [comment]
> can u provide example how to use it? I don't understand how to use this.

all samples are there： https://github.com/asjqkkkk/markdown_widget/tree/master/example
this is for users to use markdown_widget
