### ISSUE TITLE
Slow and Lagging scrolling when used with ListView(MarkdownGenerator...)

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#3]
I have a large text that works very well and fast with MarkdownWidget, but when I put it in MarkdownGenerator it starts lagging.
From:
`MarkdownWidget(data: data);`
To:
 `ListView(children: MarkdownGenerator(data: data).widgets);`
So i need it for scrollable controller which is available only in ListView

**Comment by asjqkkkk** [comment]
> I have a large text that works very well and fast with MarkdownWidget, but when I put it in MarkdownGenerator it starts lagging.
> From:
> `MarkdownWidget(data: data);`
> To:
> `ListView(children: MarkdownGenerator(data: data).widgets);`
> So i need it for scrollable controller which is available only in ListView


In fact, `MarkdownWidget ` is also rendered by `MarkdownGenerator`， maybe you could wrap your own markdown list with a `StatefulWidget`， and initial data in `initialState()` 
You can refer to the implementation of `MarkdownWidget` 😄

**Comment by mrpvb-pvbk** [comment]
> You can refer to the implementation of MarkdownWidget
But how?

> In fact, MarkdownWidget is also rendered by MarkdownGenerator， maybe you could wrap your own markdown list with a StatefulWidget， and initial data in initialState()
I do.

**Comment by asjqkkkk** [comment]
> > You can refer to the implementation of MarkdownWidget
> > But how?
> 
> > In fact, MarkdownWidget is also rendered by MarkdownGenerator， maybe you could wrap your own markdown list with a StatefulWidget， and initial data in initialState()
> > I do.

such as this
```
  List<Widget> widgets = [];
  MarkdownGenerator markdownGenerator;

  @override
  void initState() {
    markdownGenerator = MarkdownGenerator(
      data: widget.data,
      childMargin: widget.childMargin,
    );
    tocList.addAll(markdownGenerator.tocList);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
            itemBuilder: (ctx, index) => widgets[index],
            itemCount: widgets.length,
            controller: YourScrollController(),
          );
  }


```

**Comment by mrpvb-pvbk** [comment]
> > > You can refer to the implementation of MarkdownWidget
> > > But how?
> > 
> > 
> > > In fact, MarkdownWidget is also rendered by MarkdownGenerator， maybe you could wrap your own markdown list with a StatefulWidget， and initial data in initialState()
> > > I do.
> 
> such as this
> 
> ```
>   List<Widget> widgets = [];
>   MarkdownGenerator markdownGenerator;
> 
>   @override
>   void initState() {
>     markdownGenerator = MarkdownGenerator(
>       data: widget.data,
>       childMargin: widget.childMargin,
>     );
>     tocList.addAll(markdownGenerator.tocList);
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return ListView.builder(
>             itemBuilder: (ctx, index) => widgets[index],
>             itemCount: widgets.length,
>             controller: YourScrollController(),
>           );
>   }
> ```

`The argument type 'LinkedHashMap<int, Toc>' can't be assigned to the parameter type 'Iterable<Widget>'.`
Problem of this
```
 MarkdownGenerator(data: data, childMargin: EdgeInsets.all(10));
            widgets.addAll(markdownGenerator.tocList); //can u explain where did u use tocList.? I'm tried to use widgets. but it doesn't works
```
I'm so sorry but i dont understand what to do :(

**Comment by asjqkkkk** [comment]
😅sorry, it shuold be markdownGenerator.widgets

tocList is used to implement TOC function

**Comment by mrpvb-pvbk** [comment]
Yea. My bad)
