### ISSUE TITLE
List incorrect rendering - location of the item

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#30]
**Describe the bug**
I use this  **data**:
`- Разработчики`
The element itself is too high, and the distance between the point and the text is small.
![Screenshot (10)87](https://user-images.githubusercontent.com/44783405/83053143-f23ef580-a058-11ea-8763-3f75b41977b6.png)
![Screenshot (10)87](https://user-images.githubusercontent.com/44783405/83053219-16023b80-a059-11ea-90b8-9dec2b41c21b.png)

**Comment by asjqkkkk** [comment]
you can custom it with `UlConfig`

![image](https://user-images.githubusercontent.com/30992818/83087352-b3925500-a0c3-11ea-8ef6-76b161b84fc2.png)

**Comment by mrpvb-pvbk** [comment]
It would be nice to see this by default.
