### ISSUE TITLE
[Question] Line counter in the code block

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#31]
I want to add a counter like here. With the ability to enable it at any time.
![image](https://user-images.githubusercontent.com/44783405/83053710-d5ef8880-a059-11ea-8e56-47ce41668e97.png)
How do I implement this?

**Comment by asjqkkkk** [comment]
This feature is only works with source data

But markdown is for rendering source data, so maybe you need another package to do this

**Comment by mrpvb-pvbk** [comment]
Which one? Can you give an example?

**Comment by asjqkkkk** [comment]
> Which one? Can you give an example?

I don't konw, but it's not hard to achieve
