### ISSUE TITLE
LaTex Support

### ISSUE THREAD

**Issue by equisbacon** [asjqkkkk/markdown_widget#33]
It would be cool if we could render LaTex expressions, I tried but didn't figure out how to make it using CustomWidget and flutter_svg

**Comment by asjqkkkk** [comment]
using custon tag in markdown:
```
<avatar size="12" name="tom" />
```

dart code:
```
      MarkdownWidget(
        data: data,
            styleConfig: StyleConfig(
              pConfig: PConfig(
                custom: (m.Element node) {
                  if(node.tag == 'avatar') return YourAvatarWidget();
                  ...
                  return YourCustomWidget();
                },
              ),
            ),
          ),
```

Because this package is parsed based on [markdown](https://github.com/dart-lang/markdown)

I don’t know too much about the LaTex format, and I don’t know if [markdown](https://github.com/dart-lang/markdown) supports this format. Maybe you can use `custom` tag or ask if [markdown](https://github.com/dart-lang/markdown) support this

**Comment by equisbacon** [comment]
I managed to render LaTex with custom tags, but I'm facing some problems with line breaks, every when I have three different p styles if the third one is bigger than the remaining line space, it breaks to next line 
![image](https://user-images.githubusercontent.com/47310304/86994569-1a079a00-c17d-11ea-8603-db824534eaee.png)
![image](https://user-images.githubusercontent.com/47310304/86994620-41f6fd80-c17d-11ea-8dd9-8bf356a88e4c.png)

Is there any way to solve it?

**Comment by shujaatak** [comment]
@equisbacon Can you please tell how you managed to render LaTex with custom tags?

**Comment by SSebigo** [comment]
@equisbacon how did you manage to have LaTeX support ? Did you use something like, ```<formula formula="x_2">``` or did you figure out a way to have markdown style tags (```$x_2$```)?
