### ISSUE TITLE
Persisting Checkbox State

### ISSUE THREAD

**Issue by yogeshkumar98103** [asjqkkkk/markdown_widget#34]
I am creating a notes app and I want to persist the checkbox state.
Is is possible to modify the actual string to incorporate these changes.

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/84014774-707e8e80-a9ad-11ea-8bc4-46ecb1f17e9e.png)

This package currently only supports displaying markdown data, if you apply what you changes
If you want to get the modified data, you may need to implement this function in other ways

**Comment by yogeshkumar98103** [comment]
I have figured out a way to it.
