### ISSUE TITLE
pConfig rendering error after changed TextStyle

### ISSUE THREAD

**Issue by mrpvb-pvbk** [asjqkkkk/markdown_widget#35]
**Describe the bug**
I used this:
```
pConfig: PConfig(
                                    textStyle: TextStyle(fontFamily: 'Verdana'),
                                    selectable: false,
                                    linkGesture: (linkChild, url) =>
                                        GestureDetector(
                                          child: linkChild,
                                          onTap: () => _launchURL(url),
                                        )),
```
Where did the white text come from?
![Screenshot_20200610-174001](https://user-images.githubusercontent.com/44783405/84281712-93da4280-ab41-11ea-93b4-f1dfd5e0fc1c.jpg)

Full code of my Widget:
```
 SliverList(
                    delegate: SliverChildListDelegate(MarkdownGenerator(
                            data: snapshot.data,
                            childMargin: EdgeInsets.symmetric(
                                horizontal: 10.0, vertical: 5.0),
                            styleConfig: StyleConfig(
                                imgBuilder: (String url, attributes) {
                                  return Image.file(
                                      File('$_localPath/${widget.sName}/$url'));
                                },
                                markdownTheme: (Theme.of(context).brightness ==
                                        Brightness.dark)
                                    ? MarkdownTheme.darkTheme
                                    : MarkdownTheme.lightTheme,
                                pConfig: PConfig(
                                    textStyle: TextStyle(fontFamily: 'Verdana'),
                                    selectable: false,
                                    linkGesture: (linkChild, url) =>
                                        GestureDetector(
                                          child: linkChild,
                                          onTap: () => _launchURL(url),
                                        )),
                                tableConfig: TableConfig(
                                  wrapBuilder: (table) => SingleChildScrollView(
                                    scrollDirection: Axis.vertical,
                                    child: table,
                                  ),
                                  bodyChildWrapper: (child) => Padding(
                                    padding: EdgeInsets.all(8.0),
                                    child: child,
                                  ),
                                  headChildWrapper: (child) => Padding(
                                    padding: EdgeInsets.all(8.0),
                                    child: child,
                                  ),
                                  headerStyle:
                                      TextStyle(fontWeight: FontWeight.bold),
                                ),
                                olConfig: OlConfig(
                                    indexWidget: (int deep, int index) =>
                                        Text('${index + 1}.')),
                                preConfig: PreConfig(
                                    preWrapper: (preWidget, text) {
                                      return Stack(
                                        children: <Widget>[
                                          preWidget,
                                          Align(
                                            alignment: Alignment.topRight,
                                            child: IconButton(
                                                icon: Icon(Icons.content_copy),
                                                onPressed: () {
                                                  Clipboard.setData(
                                                      new ClipboardData(
                                                          text: text));
                                                  Scaffold.of(context)
                                                      .showSnackBar(SnackBar(
                                                          content: Text(
                                                              'Код скопирован')));
                                                }),
                                          )
                                        ],
                                      );
                                    },
                                    theme: (Theme.of(context).brightness ==
                                            Brightness.dark)
                                        ? theme.vs2015Theme
                                        : theme.doccoTheme)))
                        .widgets),
                  ),
```
**Platform**
Does the problem appear on the **Web** or on the **Mobile**？
**-Mobile**

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/84341662-3e03aa00-abd6-11ea-800c-c009b7359b71.png)

can you provide a minimal sample project，😂I can't locate this issue

**Comment by asjqkkkk** [comment]
is your markdown version 1.2.0 ?
maybe this issue is caused by dark mode, test for

```
  markdown_widget:
    git:
      url: https://github.com/asjqkkkk/markdown_widget.git
      ref: dev
```

**Comment by mrpvb-pvbk** [comment]
Wait i will make example and send to u

**Comment by mrpvb-pvbk** [comment]
This is so strange. I used the same library and created a new project and everything worked there. I'm confused.

**Comment by asjqkkkk** [comment]
> This is so strange. I used the same library and created a new project and everything worked there. I'm confused.

This is a issue has been solved in #32 😂，it will be fix in v1.2.1

**Comment by mrpvb-pvbk** [comment]
Here is a project where there is a rendering error https://github.com/mrpvb-pvbk/issue_md

**Comment by mrpvb-pvbk** [comment]
I hope this solved too #36

**Comment by asjqkkkk** [comment]
> Here is a project where there is a rendering error https://github.com/mrpvb-pvbk/issue_md

I thinkd the problem is 
```
textStyle: TextStyle(fontFamily: 'Verdana'),
```

**Comment by mrpvb-pvbk** [comment]
> > Here is a project where there is a rendering error https://github.com/mrpvb-pvbk/issue_md
> 
> I thinkd the problem is
> 
> ```
> textStyle: TextStyle(fontFamily: 'Verdana'),
> ```

No. When i delete this nothing happens.

**Comment by mrpvb-pvbk** [comment]
> > Here is a project where there is a rendering error https://github.com/mrpvb-pvbk/issue_md
> 
> I thinkd the problem is
> 
> ```
> textStyle: TextStyle(fontFamily: 'Verdana'),
> ```

I think the problem from theme.

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/84362899-8637c200-ac00-11ea-9f48-563b8e643614.png)

![image](https://user-images.githubusercontent.com/30992818/84362934-93ed4780-ac00-11ea-944a-c89683612869.png)

you did not declare your font in pubspec.yaml

**Comment by mrpvb-pvbk** [comment]
That's not the point. The font itself turns white when I add a line with theme. The font can be removed and then nothing will change.

**Comment by mrpvb-pvbk** [comment]
> ![image](https://user-images.githubusercontent.com/30992818/84362899-8637c200-ac00-11ea-9f48-563b8e643614.png)
> 
> ![image](https://user-images.githubusercontent.com/30992818/84362934-93ed4780-ac00-11ea-944a-c89683612869.png)
> 
> you did not declare your font in pubspec.yaml

I can also write this font in pubspec.yml and nothing will happen. In my main application, all this is spelled out. And the font works everywhere and throughout the app.

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/84363530-779dda80-ac01-11ea-9f22-0e9983f8c35a.png)

when I delete this line ,it looks ok

**Comment by mrpvb-pvbk** [comment]
> ![image](https://user-images.githubusercontent.com/30992818/84363530-779dda80-ac01-11ea-9f22-0e9983f8c35a.png)
> 
> when I delete this line ,it looks ok

I will update my project and u will see where is problem

**Comment by mrpvb-pvbk** [comment]
I am update example project check it out

**Comment by asjqkkkk** [comment]
> I am update example project check it out

![image](https://user-images.githubusercontent.com/30992818/84367369-bb471300-ac06-11ea-877f-dd27d199991e.png)

Is this your problem?

try to change `markdown_widget` in pubspec.yaml file

```
  markdown_widget:
    git:
      url: https://github.com/asjqkkkk/markdown_widget.git
      ref: dev
```

**Comment by mrpvb-pvbk** [comment]
I did, but nothing changed

**Comment by asjqkkkk** [comment]
I konw what's the problem, you need to declare `TextStyle` with `fontFamily` and other properties.
or use code like that:
```
defaultPStyle.merge(TextStyle(fontFamily: 'Verdana'))
```
