### ISSUE TITLE
Font size of link tag does not follow font size of setup in android 10 on pixel 2XL

### ISSUE THREAD

**Issue by honzasvasek** [asjqkkkk/markdown_widget#37]
On pixel 2XL in setup -> display -> advanced you can change the overall fontsize for the phone.

In this widget the link tag font is not properly sized when the overall fontsize is changed from default.

![Screenshot_20200615-104918](https://user-images.githubusercontent.com/11519542/84620592-0ce8e980-aef6-11ea-895f-8a619de5b0ea.png)
![Screenshot_20200615-104834](https://user-images.githubusercontent.com/11519542/84620599-0fe3da00-aef6-11ea-8eb1-152292756165.png)

Free Butoh School is the link tag.

**Comment by asjqkkkk** [comment]
It seems strange, maybe set a fontSize to `PConfig` with `linkStyle` can make it work
