### ISSUE TITLE
[Feature request] Editor mode?

### ISSUE THREAD

**Issue by liudonghua123** [asjqkkkk/markdown_widget#38]
**Is your feature request related to a problem? Please describe.**
I want to use a markdown editor, but most of them I found is based on webview. It's slow and heavy.

**Describe the solution you'd like**
Provide `readonly` or `editable` attributes for configuration.

**Comment by asjqkkkk** [comment]
可以参考一下这个仓库里面提供的demo，看看想实现一个编辑器是怎么做的😂

**Comment by liudonghua123** [comment]
@asjqkkkk 不好意思呀，没有仔细看demo 😂

**Comment by liudonghua123** [comment]
我看 demo 里面的 markdown editor 是一个纯文本输入框，要是添加上一些工具栏按钮、实时预览或者其他的就比较方便了 😄

**Comment by asjqkkkk** [comment]
> 我看 demo 里面的 markdown editor 是一个纯文本输入框，要是添加上一些工具栏按钮、实时预览或者其他的就比较方便了 😄

因为是demo，所以没打算弄的太复杂，而且编辑功能的话其实已经超出这个库的范畴了😄
