### ISSUE TITLE
Add onLinkLongPress option to PConfig

### ISSUE THREAD

**Issue by TheBestMoshe** [asjqkkkk/markdown_widget#4]
Within `PConfig`, in addition to `onLinkTap` would it possible to add an `onLinkLongPress` option? 

My specific use case would be to have an option to share the link without opening it.

**Comment by asjqkkkk** [comment]
it's very easy, and it's a very useful use case

**Comment by asjqkkkk** [comment]
> Within `PConfig`, in addition to `onLinkTap` would it possible to add an `onLinkLongPress` option?
> 
> My specific use case would be to have an option to share the link without opening it.

Hi,
you can update to v1.0.9
and use like this
```
        styleConfig: StyleConfig(
          pConfig: PConfig(
            linkGesture: (linkChild, url) {
              return GestureDetector(
                child: linkChild,
                onTap: () => _launchURL(url),
                onLongPress: => yourLongPressLogic(),
              );
            },
          ),
        ),
```

**Comment by TheBestMoshe** [comment]
This is perfect. Thank you!!
