### ISSUE TITLE
Monospace font missing from output

### ISSUE THREAD

**Issue by siliconsorcery** [asjqkkkk/markdown_widget#45]
**Describe the bug**
Code blocks and inline `pre` blocks are not presented with a monospace font.

**To Reproduce**
1.  [Run online demo](https://oldchen.top/markdown_widget/#/) 

**Expected behavior**
Code example should be color highlighted using a monospace font.
Inline blocks should be using a monospace font.

**Environment(please complete the following information):**
Using Chrome with web example
Also, tried building Flutter App for iOS 14 with same results.

**Platform**
Chrome, iOS

**Comment by asjqkkkk** [comment]
hi, can you provider some scrennshots or a minimal project to describe it more clearly😄

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/93547834-89c5ac80-f998-11ea-93c8-62965423dd52.png)

`pre` block's font default to be 12, you can set it with `PreConfig`,

**Comment by van-8** [comment]
This is not a bug, just a style preference. I do agree this is a nice default style to have though. 

Submitted PR #47 for your consideration @asjqkkkk . Love the package!

**Comment by asjqkkkk** [comment]
This issue is too old, if necessary, please create an new issue
