### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by the-thirteenth-fox** [asjqkkkk/markdown_widget#5]
It would be cool to see documentation on all the features of this plugin.

**Comment by asjqkkkk** [comment]
I think the current README is enough to support the use of this package

So the priority of the features documentation  will not be too high😅

Maybe later I will take the time to make a simple document

**Comment by mrpvb-pvbk** [comment]
> I think the current README is enough to support the use of this package
> 
> So the priority of the features documentation will not be too high😅
> 
> Maybe later I will take the time to make a simple document

How to change the main theme? Now it's like github. So if ill use pConfig it takes a long time to change all the config settings

**Comment by asjqkkkk** [comment]
> > I think the current README is enough to support the use of this package
> > So the priority of the features documentation will not be too high😅
> > Maybe later I will take the time to make a simple document
> 
> How to change the main theme? Now it's like github. So if ill use pConfig it takes a long time to change all the config settings

In actually, there is no theme for markdown_widget, you can only set theme for `HighLight Code View` 

and what dose ` if ill use pConfig it takes a long time to change all the config settings` mean? 😅

**Comment by mrpvb-pvbk** [comment]
> > > I think the current README is enough to support the use of this package
> > > So the priority of the features documentation will not be too high😅
> > > Maybe later I will take the time to make a simple document
> > 
> > 
> > How to change the main theme? Now it's like github. So if ill use pConfig it takes a long time to change all the config settings
> 
> In actually, there is no theme for markdown_widget, you can only set theme for `HighLight Code View`
> 
> and what dose ` if ill use pConfig it takes a long time to change all the config settings` mean? 😅

Sorry for my English)) Im still studying. This means that to change the current theme, you will have to change the parameters in the config(pConfig, blocConfig and so on) for a long time.

_I have one more question._ How to use widgetConfig?

**Comment by asjqkkkk** [comment]
> > > > I think the current README is enough to support the use of this package
> > > > So the priority of the features documentation will not be too high😅
> > > > Maybe later I will take the time to make a simple document
> > > 
> > > 
> > > How to change the main theme? Now it's like github. So if ill use pConfig it takes a long time to change all the config settings
> > 
> > 
> > In actually, there is no theme for markdown_widget, you can only set theme for `HighLight Code View`
> > and what dose ` if ill use pConfig it takes a long time to change all the config settings` mean? 😅
> 
> Sorry for my English)) Im still studying. This means that to change the current theme, you will have to change the parameters in the config(pConfig, blocConfig and so on) for a long time.
> 
> _I have one more question._ How to use widgetConfig?

Yes, if you want to change the theme, you need prepare for different `xxxConfig` code

`WidgetConfig`  provide the original markdown Element tag data to the user, so that the user can customize the corresponding widget through these data.
But if you don't know much about the tag format of markdown, it's not recommended to use this function
