### ISSUE TITLE
TOC text is clipped

### ISSUE THREAD

**Issue by joe-getcouragenow** [asjqkkkk/markdown_widget#50]
**Describe the bug**
TOC text is clipped

**To Reproduce**

**Expected behavior**
Not be clipped

**Screenshots**
![Screenshot 2020-11-05 at 15 19 51](https://user-images.githubusercontent.com/59567750/98252626-725b7680-1f7a-11eb-8a99-ea2ec3914d01.png)

Desktop - toc test is ok. But the Responsive Design thinks its mobile :) Different issue.
![Screenshot 2020-11-05 at 15 28 58](https://user-images.githubusercontent.com/59567750/98253700-abe0b180-1f7b-11eb-8f5d-53a2ba49e532.png)

**Environment(please complete the following information):**

flutter  channel dev

**Platform**
Does the problem appear on the **Web** or on the **Mobile**？
Web has the bug.
Mobile and Desktop does not.

**Additional context**

**Comment by asjqkkkk** [comment]
Hi, I have met his issue, it should be flutter's issue😄
