### ISSUE TITLE
Video cant be stopped

### ISSUE THREAD

**Issue by joe-getcouragenow** [asjqkkkk/markdown_widget#51]
**Describe the bug**
The video cant be stopped when you click on it. Even though the pause icon appears on hover.

**To Reproduce**

**Expected behavior**
Should pause or stop.

**Screenshots**

**Environment(please complete the following information):**
flutter channel dev.

**Platform**
Does the problem appear on the **Web** or on the **Mobile**？
Web

**Additional context**

**Comment by asjqkkkk** [comment]
Hi, could you provider you flutter environment for me to locate and solve this issue?

**Comment by asjqkkkk** [comment]
maybe this will help you : https://github.com/asjqkkkk/markdown_widget/blob/master/example/lib/markdown_custom/video.dart
