### ISSUE TITLE
off-line ability to show images

### ISSUE THREAD

**Issue by johnareid54** [asjqkkkk/markdown_widget#58]
Great package, I am using it for Markdown text held in firebase storage and then downloaded locally to a Hive database, and it is working just fine.
The Markdown has both text and images (i.e. a http address).  What happens when the app has no internet connection  - will the images still be shown?
Or should I loop through the Markdown text, find the links download as files and change the link in the markdown entry?

Really hoping this has already been done!

**Comment by asjqkkkk** [comment]
Hi, you can use `imageBuilder` to custom your image widget
```
  Widget buildMarkdown() => MarkdownWidget(
        data: data,
        styleConfig: StyleConfig(
          imgBuilder: (String url,attributes) {
            return Image.network(url);
          },
          videoBuilder: (String url,attributes) {
            return YourVideoWidget();
          }
        ),
      );
```
for example, you can use `CachedNetworkImage` to replace the default Image widget
