### ISSUE TITLE
The getter 'selectable' was called on null.

### ISSUE THREAD

**Issue by liudonghua123** [asjqkkkk/markdown_widget#6]
I use some code like this
```dart
  @override
  Widget build(BuildContext context) {
    String data =
        '[Welcome for pull request](https://github.com/asjqkkkk/markdown_widget)😄\n\n';
    return Column(
      children: [
        ...MarkdownGenerator(
          data: data,
          // styleConfig: StyleConfig(
          //   ulConfig: UlConfig(
          //     dotWidget: (int deep, int index) => Icon(Icons.android),
          //   ),
          // ),
        ).widgets,
        constructTag('标签', ['吉他', '弹指', '唱奏', '大师'])
      ],
    );
  }
```

Then I got the following error

![image](https://user-images.githubusercontent.com/2276718/79710524-cf9e1c00-82f7-11ea-8348-eb4f0621c3df.png)

**Comment by asjqkkkk** [comment]
Thank you, it's a broken update by v1.0.9😅
I'll fix it quickly

**Comment by asjqkkkk** [comment]
看到中文了，我直接用中文回复吧😄
这个issue在v1.1.0被修复了，可以直接通过升级来解决这个问题
如果不想升级的话，在 `StyleConfig` 配置一下 `PConfig` 就行，这是由v1,0.9带来的破坏性修复😅

**Comment by liudonghua123** [comment]
嗯，我刚才也试着直接修改源码的方式，设置默认值可以解决，既然有新版本，那我就直接升级了。

在使用过程中发现字体的颜色这块是固定的，建议可以使用主题集成下来的颜色（大小不确定主题里面有没有定义）

谢谢 :)

**Comment by liudonghua123** [comment]
我刚发现你才上传的新版本 https://pub.dev/packages/markdown_widget/versions ，我大概十分钟之前安装的还是 1.0.9 旧版本 😃

**Comment by asjqkkkk** [comment]
对，我刚刚升级就是修复这个issue

根据主题来设置颜色可以是一个很好的feature，不过这个需求不是必须的，而且可能修改的地方会比较多，我一个人精力不够

如果可以的话，可以通过提pr的方式来完成这个功能😂
