### ISSUE TITLE
on Desktop does not render images or video due to no network connectivity. Easy to fix by adding these to mac and ios plist for debug and release

### ISSUE THREAD

**Issue by gedw99** [asjqkkkk/markdown_widget#61]
**Describe the bug**

On Desktop the images and video wont render because the rights are not enabled.

**Expected behavior**

Renders images and video.

**This fix**

You need to add:
```
<key>com.apple.security.network.client</key>
<true/>
``` 
to 
macos/Runner/DebugProfile.entitlements 
and 
macos/Runner/Release.entitlements

Its documented here: https://flutter.dev/desktop#entitlements-and-the-app-sandbox

**Screenshots**

![Screenshot 2021-04-19 at 11 25 43](https://user-images.githubusercontent.com/53147028/115213635-00c74d00-a102-11eb-8ffe-48c021d1ec66.png)

**Environment(please complete the following information):**
Please use `flutter doctor -v` to show your flutter enviroment

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.2.0-10.1.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-DE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

**Platform**
desktop mac.

**Environment**
mac

**Comment by asjqkkkk** [comment]
Hi, I think this is not a bug to this package
It should be a network config issue for a project
