### ISSUE TITLE
Does it support checkbox right click with out manually editing?

### ISSUE THREAD

**Issue by jinfagang** [asjqkkkk/markdown_widget#65]
Does it support checkbox right click with out manually editing?

**Comment by asjqkkkk** [comment]
> @asjqkkkk hi, I mean checkbox can click, and direcly add a `-` in `- [ ]` so that it will automatically support :
> 
> from
> 
> * [ ]
> 
> to
> 
> * [x]
> 
> and save automatically, does this can done easily?

Hi, it's not supported now, `markdown_widget` only display data, it will not save data

**Comment by jinfagang** [comment]
@asjqkkkk I notice that many APP support this feature by default, such as iOS Notes, anyother app can do this. Do u think it possible by simply speciffy a click builder?

**Comment by asjqkkkk** [comment]
> @asjqkkkk I notice that many APP support this feature by default, such as iOS Notes, anyother app can do this. Do u think it possible by simply speciffy a click builder?

there is `CheckBoxBuilder` --- `typedef Widget CheckBoxBuilder(bool checked, Map<String, String> attributes);`
you can use that to save data in your app
