### ISSUE TITLE
Checkbox not rendering correctly

### ISSUE THREAD

**Issue by tobiasht** [asjqkkkk/markdown_widget#68]
**Describe the bug**
Checkboxes only support `[ ]` and not `- [ ]` which is the more common way of writing it. I do not want to change my markdown file to work with this package.

[GitHub´s markdown reference](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

**Comment by asjqkkkk** [comment]
Yes, Now only support 
`[]` and `[x]`

perhaps I need time to fix it

**Comment by asjqkkkk** [comment]
Hi, now use v1.3.0, and `- [ ]` can be recognized
but it will perform like this:
![image](https://user-images.githubusercontent.com/30992818/190342803-eb3d9b1f-7846-4d32-b1f8-d40abbd0d132.png)
