### ISSUE TITLE
Support flutter 3.0

### ISSUE THREAD

**Issue by hs029** [asjqkkkk/markdown_widget#69]
Upgrade to flutter 3.0 and compile, see issue:

flutter/.pub-cache/hosted/pub.flutter-io.cn/scrollable_positioned_list-0.2.3/lib/src/positioned_list.dart:312:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../appdev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^

**Comment by asjqkkkk** [comment]
now v1.2.9 support flutter 3.0
