### ISSUE TITLE
Unexpected line break after styling text

### ISSUE THREAD

**Issue by ManonLecareux** [asjqkkkk/markdown_widget#70]
**Describe the bug**
Text wraps when a sentence is bold/italicized/... which does not happen when only a word is styled.

This is sended markdown:
 du **gras** et de l'_italique_ et du ~~barré~~ ! 

text ever since the 1500s, when an unknown printer **took a galley of type and scrambled it to make a type specimen** book. It has survived not only five centuries, young _but also the leap into electronic typesetting for nox_, remaining essentially unchanged. It was very very  ~~popularised in the 1960s~~ with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

And this is result : 
<img width="376" alt="Capture d’écran 2022-09-01 à 16 31 37" src="https://user-images.githubusercontent.com/103517589/187940272-803df4e6-22af-4770-9753-59d340ff5694.png">

**Expected behavior**
Only one paragraph

**Environment**
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.5.1 21G83 darwin-x64, locale fr)
    • Flutter version 3.0.4 at /Users/mlecareux/fvm/versions/3.0.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (9 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mlecareux/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/mlecareux/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.40.0

[✓] VS Code (version 1.55.2)
    • VS Code at /Users/mlecareux/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 105.0.5195.52

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by asjqkkkk** [comment]
Hi, can you switch dev branch to make a test? Maybe this issue has been solved.
![image](https://user-images.githubusercontent.com/30992818/190315680-14f8f85e-3203-4add-8212-e689cf9a9f8e.png)

**Comment by asjqkkkk** [comment]
now v1.3.0 was published, you can check if the issue is still exist

**Comment by ManonLecareux** [comment]
Yes thanks is resolved on this version !
