### ISSUE TITLE
How do custom tags work with non HTML style tags?

### ISSUE THREAD

**Issue by SSebigo** [asjqkkkk/markdown_widget#72]
I want to integrate a widget to display maths/physics formulas with LaTeX, but I can't seem to make it detect the tag ```$formula$```.
Is there a special way to detect Markdown style tags?

**Comment by asjqkkkk** [comment]
Now `LaTex` is not supported,
perhaps you can try to use `custom` tag to resolve `LaTex` by yourself

![image](https://user-images.githubusercontent.com/30992818/194356365-0b7b05ec-8606-4571-9784-54f414d6d41a.png)

**Comment by SSebigo** [comment]
@asjqkkkk I am using it, the problem is that it requires HTML style, e.g. ```<tag data="">```, but what I'm looking for is something like a base Markdown tagging, e.g. ```tag```data```tag```.

**Comment by asjqkkkk** [comment]
Yes, I found out what the problem was.
The text which has not been recognized will finally rendered as `text` tag
I need to improve the structure of this library to support define more **tags**

**Comment by PRO-BROS** [comment]
I'm also trying to use it in my [site](https://prhocoding.com/)

**Comment by asjqkkkk** [comment]
in `markdown_widget 2.0.0+` that you can extend the package to support this feature by using the [html_support](https://github.com/asjqkkkk/markdown_widget/blob/dev/example/lib/markdown_custom/html_support.dart)
