### ISSUE TITLE
Align text with latex

### ISSUE THREAD

**Issue by NicolasLaube** [asjqkkkk/markdown_widget#75]
Hi,
First, thank you for your amazing package!

My concerns the custom tags.
I add latex to the text by adding a `<latex id=x />` tag in a text.

However, I have an issue: 
- The text isn't aligned with the latex

<img width="434" alt="image" src="https://user-images.githubusercontent.com/45005101/211208854-f2a2d1d1-909c-421d-a2d9-82ba2f67ada2.png">

For example, here is a text with latex I might use (sorry for the french..) :
```
Nous avons : <latex id=1 /> Ainsi, si latex id=2 /> alors <latex id=3 />, <latex id=4 /> et 
<latex id=5 /> <latex id=6 /> ont les mêmes polynômes et les même valeurs propres. 
Sinon, <latex id=7 /> ce qui est impossible puisque  <latex id=8 /> est symétrique et 
diagonalisable. Les valeurs propres ne sont pas mêmes : Prenons <latex id=9 />. 
Alors, latex id=10 /> est un vecteur propre de latex id=11 /> car <latex id=12 /> et
 latex id=13 /> alors que  <latex id=14 /> et <latex id=15 />.
```

To display a `latex` gap, I use the `flutter_math_fork` package :
```
Math.tex(
                        content,
                        mathStyle: MathStyle.text,
                        textStyle:
                            textStyle ?? Theme.of(context).textTheme.bodyLarge,
                        textScaleFactor: textScaleFactor,
                        onErrorFallback: (err) {
                          LOGGER.e(err.messageWithType);
                          return SizedBox.shrink();
                        },
                      )
```

I use this package for iOS, Android and web.
Flutter doctor displays no issues..

**Comment by asjqkkkk** [comment]
Hi, I'm also intersted in `latex`, I use `markdown_widget 2.0` to implement it

![image](https://user-images.githubusercontent.com/30992818/211343499-ee785325-3af6-4c52-b3dd-c7d3005e72fc.png)

but there are some changes, you can use this version, before I update it:
```
  markdown_widget:
    git:
      url: https://github.com/asjqkkkk/markdown_widget.git
      ref: dev
```

**Comment by asjqkkkk** [comment]
The align text with latex is still a problem, I'm looking for a easy way to solve it

**Comment by asjqkkkk** [comment]
Hi, @NicolasLaube can you see if this effetc is ok? 
![image](https://user-images.githubusercontent.com/30992818/211566725-524367cb-7770-4e4a-8bdb-a77725ab7dae.png)
