### ISSUE TITLE
Problems with "Selection"

### ISSUE THREAD

**Issue by ivictoruan** [asjqkkkk/markdown_widget#76]
**Describe the bug**
When I try to run the program shows erros with _Selection_

Launching lib\main.dart on SM G935F in debug mode...
lib\main.dart:1
: Error: The method 'SelectionArea' isn't defined for the class '_MarkdownWidgetState'.
package:markdown_widget/widget/markdown.dart:136
- '_MarkdownWidgetState' is from 'package:markdown_widget/widget/markdown.dart' ('../../../../../../Documents/src/flutter/.pub-cache/hosted/pub.dartlang.org/markdown_widget-2.0.0+1/lib/widget/markdown.dart').
package:markdown_widget/widget/markdown.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'SelectionArea'.
        ? SelectionArea(child: markdownWidget)
          ^^^^^^^^^^^^^

: Error: The getter 'SelectionContainer' isn't defined for the class '_OlMarker'.
package:markdown_widget/…/container/list.dart:199
- '_OlMarker' is from 'package:markdown_widget/widget/blocks/container/list.dart' ('../../../../../../Documents/src/flutter/.pub-cache/hosted/pub.dartlang.org/markdown_widget-2.0.0+1/lib/widget/blocks/container/list.dart').
package:markdown_widget/…/container/list.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'SelectionContainer'.

    return SelectionContainer.disabled(
           ^^^^^^^^^^^^^^^^^^
2

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\victo\Documents\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

**Comment by asjqkkkk** [comment]
Hi, perhaps you are using a flutter version lower than 3.3

Could you provider your `markdown_widget` version and your `flutter doctor` log?

**Comment by asjqkkkk** [comment]
This issue is too old, if necessary, please create an new issue
