### ISSUE TITLE
How to add the support for HTML

### ISSUE THREAD

**Issue by JohnF17** [asjqkkkk/markdown_widget#77]
### The issue
Hi, i know i'm missing something here as I really shouldn't be opening an issue for what i guess is probably a very easy issue to solve😅
But here's what I need help with
I want to parse this markdown to include support for this markdown-html below
```
# Topic: User Data Not Found 
<div style="display:inline-block;background-color:red;border-radius: 50%; color:white; padding:5px;float:right;">
  Error code: e209
</div>
...
...
```

---

### What i want to implement
So what i want is to have this red error code container at the top right on the same line as the topic header.

---

I have seen the documentation that refers to the `html_Support.dart` file, i just have no clue on how to implement it as there isn't any documentation on how to use it with the `markdown_widget`.
P.s I have also checked if this `div` worked here on github markdown preview but it just ignores all the properties and shows the text, so i'm guessing that might be the case for the markdown_widget parsing it, so i would really appreciate it if you can also give me a workaround on how i could implement this below. 
> red error code container at the top right on the same line as the topic header.

**Comment by JohnF17** [comment]
So apparently
> "GitHub Flavored Markdown" (GFM) allows some HTML tags, but it doesn't include all the HTML tags and it doesn't allow CSS styles.

So that explains why it doesn't work here 🤔 so the second question now becomes does this package support CSS styling on Html and if not is there a workaround for what i want to achieve with this below
> red error code container at the top right on the same line as the topic header.

And of course the main question, how do i use `html.support.dart` ? 😅

**Comment by asjqkkkk** [comment]
Hi, I wrote a test file to show a sample for `div` tag, see [html_test](https://github.com/asjqkkkk/markdown_widget/blob/dev/example/test/html_test.dart)

you can convert `attribute` to Container with various style

**Comment by asjqkkkk** [comment]
And there is my code:

`div.dart`
```
import 'package:flutter/material.dart';
import 'package:markdown_widget/markdown_widget.dart';

class DivNode extends ElementNode {
  final Map<String, String> attribute;

  DivNode(this.attribute);

  @override
  InlineSpan build() => WidgetSpan(
      child: buildContainer(Text.rich(childrenSpan)));

  Widget buildContainer(Widget child) {
    return Container(
      ///TODO: implement various styles with [attribute]
      decoration: BoxDecoration(
        color: Colors.grey.withOpacity(0.3),
        borderRadius: BorderRadius.all(Radius.circular(4)),
      ),
      padding: EdgeInsets.all(4),
      child: child,
    );
  }
}

SpanNodeGeneratorWithTag divGeneratorWithTag = SpanNodeGeneratorWithTag(
    tag: 'div', generator: (e, config, visitor) => DivNode(e.attributes));
```

![image](https://user-images.githubusercontent.com/30992818/213862246-75a82b32-fae8-409e-a776-1b6d566b7e7e.png)

![image](https://user-images.githubusercontent.com/30992818/213862255-093eed0c-c872-4288-bf49-3bdc0f6299ee.png)

**Comment by JohnF17** [comment]
Hi @asjqkkkk, thank you for the reply.
I copied the code from div.dart and and applied the divGeneratorWithTag on the generators

```
MarkdownWidget(
  data: snapshot.hasData ? snapshot.data! : '# Loading...',
  config: controller.isDarkMode.value ? _darkConfig : _lightConfig,
  markdownGeneratorConfig: MarkdownGeneratorConfig(
    generators: [divGeneratorWithTag],
  ),
);
```

But It doesn't work, how do I link the DivNode to the markdown widget and is there something else i'm missing?

**Comment by asjqkkkk** [comment]
you need to use this version in .yaml file

```
  mardkown_widget:
    git:
      url: https://github.com/asjqkkkk/markdown_widget.git
      ref: dev
```

and then try it agian

**Comment by JohnF17** [comment]
Works perfect! I did a couple of adjustments also understood how to use the attributes to alter the container's properties.
Thanks 🙏
