### ISSUE TITLE
Latex preview does not work on Android and 

### ISSUE THREAD

**Issue by EquinoxM** [asjqkkkk/markdown_widget#81]
**Describe the bug**
I think it is interfering with the Markdown inline hidden text feature referring to [Hiding content with comments](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#hiding-content-with-comments)

**To Reproduce**
just downloaded the example and ran it then everything seems fine 

**Expected behavior**
Images/video/latex should be visible and show up

**Screenshots**
![image](https://user-images.githubusercontent.com/117537258/216069961-afbdce89-e94a-4113-a406-cf645ac37a4f.png)

**Platform**
Does the problem appear on the **Web** or on the **Mobile**？
yes both

**Comment by EquinoxM** [comment]
additional info since I saw that the project is using Gradle 6.7 and my project is using 7.6

**Comment by thomastthai** [comment]
The cited items work on web, Windows, and Android with the changes detailed in:

- To get the demo to work with Gradle 7.6, check out [Issue #79](https://github.com/asjqkkkk/markdown_widget/issues/79#issuecomment-1406979618).
- See [Issue #80](https://github.com/asjqkkkk/markdown_widget/issues/80) about the video.

**Comment by EquinoxM** [comment]
when running it on my phone after double checking and redoing everything like 5 times I got these errors and video still not working 
I also added the permission from the [video_player@pub.dev](https://pub.dev/packages/video_player) page and still didn't play  
and got this error which I think is related to the images not loading and not the video

```
E/FlutterJNI(26293): Failed to decode image
E/FlutterJNI(26293): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI(26293): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI(26293): 	at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
E/FlutterJNI(26293): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
E/FlutterJNI(26293): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
E/FlutterJNI(26293): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
E/FlutterJNI(26293): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:524)
``` 
I think it has to be something related to what I said in the first message that markdown is recognizing it first and flagging it as ignore in the out or something because anything I put in between <> disappears no matter what unless I do <\ > and in that case it just displays it as a normal text 

I was able to display an image using html inspect then copy element  it worked using this ctrl+c ctrl+v
and was able to get images/gifs from google drive as well as from any where on the internet
```
<img src="https://drive.google.com/uc?export=view&id=1JmjnyfuFPTp6BEWtUfPtpebCir0yGiVW"> 
```
several tries later and still can't get a video to show up but any images can now

one more note it seems like renaming images from .svg to .png works fine would love to find something for the videos and latex as well I was more interested in latex than video and got images along the way

**Comment by EquinoxM** [comment]
here is an update screen shot since I forgot to post one with a few notices
for images .svg doesn't work you need a .png image instead for it to work
and for latex equations I can't find a solution to them exceeding the screen width rn
![flutter_02](https://user-images.githubusercontent.com/117537258/216449841-aa302ec8-52e5-4162-aabb-4b710afac545.png)

**Comment by asjqkkkk** [comment]
Hi @EquinoxM , thanks for your issue
there are some problems with custom `html tags`, I'll try to improve them at next version,
and there will be more examples for how to use a custom tag, such as `Latex`

**Comment by asjqkkkk** [comment]
Hi, v2.1.0 has been published, and there are more latex samples with online demo : https://asjqkkkk.github.io/markdown_widget/#/sample_latex

you can have a look
