### ISSUE TITLE
Unable to remove inbuilt padding with simple text block

### ISSUE THREAD

**Issue by daveshirman** [asjqkkkk/markdown_widget#82]
**Describe the bug**
I'm just trying to render a text block and it seems there's a padding of 4px around everything. I want to remove it please.

**To Reproduce**
- See code below.
- Note: I've tried to remove padding with MediaQuery, but it's not doing anything that I can see:
- Note: the inner padding in the amber boxes
- Names redacted for privacy, ignore black boxes.
- Note: If I replace the Markdown widget with a standard Flutter Text() widget, the padding is gone as expected.

```
return Container(
  color: Colors.amber,
  child: DefaultTextStyle.merge(
    textAlign: TextAlign.start,
    child: MediaQuery.removePadding(
      context: context,
      removeLeft: true,
      removeRight: true,
      removeTop: true,
      removeBottom: true,
      child: MarkdownWidget(
        config: config,
        data: text,
        shrinkWrap: true,
        padding: EdgeInsets.zero,
      ),
    ),
  ),
);
```

**Expected behavior**
No padding is set when set to zero.

**Screenshots**
![Screenshot 2023-02-02 at 16 03 11](https://user-images.githubusercontent.com/14280030/216449271-89ffc73f-17e4-408b-9624-653664304bba.png)

**Environment(please complete the following information):**
```
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-x64, locale en-GB)
    • Flutter version 3.7.0 on channel stable at /Users/daveshirman/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (10 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
```

**Platform**
iOS (haven't checked Android yet)

**Comment by daveshirman** [comment]
Is setting the `markdownGeneratorConfig` the correct way to achieve this?

e.g for only vertical padding:

```
markdownGeneratorConfig: MarkdownGeneratorConfig(
  linesMargin: const EdgeInsets.symmetric(vertical: 4),
),
```

If so, please update the documentation.

**Comment by asjqkkkk** [comment]
> Is setting the `markdownGeneratorConfig` the correct way to achieve this?
> 
> e.g for only vertical padding:
> 
> ```
> markdownGeneratorConfig: MarkdownGeneratorConfig(
>   linesMargin: const EdgeInsets.symmetric(vertical: 4),
> ),
> ```
> 
> If so, please update the documentation.

Hi, @daveshirman , thanks for you issue

you can change it to `EdgeInsets.zero` to solve this issue, and I'll update the documentation next version

**Comment by daveshirman** [comment]
Thank you for your response. Setting to zero means the lines are too close
together.

I don't know if this related or should be a separate issue, but emoji
characters also cause text lines to be rendered unequally vertically too.

Any idea on how to fix that?

Thank you again

**Comment by asjqkkkk** [comment]
Hi @daveshirman , the problem caused by emojis should be an issue of Flutter.
