### ISSUE TITLE
List items are rendered far too big compared to other text - ESPECIALLY when system text size is increased with accessibility feature

### ISSUE THREAD

**Issue by daveshirman** [asjqkkkk/markdown_widget#83]
**Describe the bug**
List items, both numbered and non-numbered render far too big compared to normal text.

**To Reproduce**
1. On iOS, change in `Settings` -> `Accessibility` -> `Display & TextSize` -> `Larger Text`: make a few notches bigger.
2. Then see the app text being massive, but only for list item tags.
3. See relevant code below:

```
var text = """
This is a long paragraph sentence thing that nobody cares about but me.

1. This is a list item 
2. This is another list item

This is a title separator:

* this is a list item 
* this is another list item
""";

return DefaultTextStyle.merge(
  textAlign: TextAlign.start,      
  child: MarkdownWidget(
    data: text,
    shrinkWrap: true,
    padding: EdgeInsets.zero,
    markdownGeneratorConfig: MarkdownGeneratorConfig(
      linesMargin: const EdgeInsets.symmetric(vertical: 4),
    ),
  ),
);
```

**Expected behavior**
List items are rendered normal size.

**Screenshots**

![Screenshot 2023-02-03 at 13 52 27](https://user-images.githubusercontent.com/14280030/216683889-9671c795-60a3-425a-8f12-fb00817ad1db.png)

**Environment(please complete the following information):**
```
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-x64, locale en-GB)
    • Flutter version 3.7.0 on channel stable at /Users/daveshirman/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (10 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
```

**Platform**
iOS

**Comment by asjqkkkk** [comment]
Hi @daveshirman , I konw why it behaves like that

you can have a try with the code : 
```
return DefaultTextStyle.merge(
  textAlign: TextAlign.start,      
  child: MarkdownWidget(
    data: text,
    config: MarkdownConfig(configs: [PConfig(textStyle: TextStyle())]),
    shrinkWrap: true,
    padding: EdgeInsets.zero,
    markdownGeneratorConfig: MarkdownGeneratorConfig(
      linesMargin: const EdgeInsets.symmetric(vertical: 4),
    ),
  ),
);
```

**Comment by Andorion** [comment]
This one is a big one for me, a lot of people have larger font size set in iOS.  Different parts of the markdown scale differently, the regular text seems like it doesn't scale enough, some of them scale a ton.

**Comment by asjqkkkk** [comment]
> 

Hi @Andorion, thanks for your reply, this week I'll have enough time to work with the issue, just wait for a while

**Comment by asjqkkkk** [comment]
Hi, @Andorion @daveshirman ， I found that text behaved incorrectly with `WidgetSpan`, there was a default `textScaleFactor` value for them that had been set, and I've no idea why the behavior between `TextSpan` and `WidgetSpan` are not same

So I set `textScaleFactor` to 1.0 for some `Text.rich`, and it behaves like :

- The Largest font size : 
![image](https://user-images.githubusercontent.com/30992818/223733428-38715eca-0b5d-4936-aa4f-231e08afc21f.png)

- The Small font size :  
![image](https://user-images.githubusercontent.com/30992818/223734008-f631163b-1c20-43f4-a52c-dcb55c806d63.png)

- The Default font size :
![image](https://user-images.githubusercontent.com/30992818/223734355-74f1c9ea-ca45-48d9-9872-70d8aa488455.png)

**Comment by daveshirman** [comment]
@asjqkkkk I really do care about that paragraph, it's not just you haha!

Thanks for this. So does the text scaling accurately still work when pushed up to the max on iOS? Can't tell from your screenshots. 

Btw separate question - what are the main differences (if any) with your implementation and the one I linked from Flutter team, with regards to rendering?

Cheers.

**Comment by asjqkkkk** [comment]
Hi @daveshirman, there are some screenshots for iOS simulator
![image](https://user-images.githubusercontent.com/30992818/224207831-cfc74a35-675c-4049-8f88-19f4facd2fc9.png)
![image](https://user-images.githubusercontent.com/30992818/224207943-cffc021f-d874-4435-bd22-f46ddc2bec33.png)
It looks fine

**Comment by asjqkkkk** [comment]
Hi everyone, this issue has been solved by v2.1.0
you can upgrade to that version to have a check

**Comment by daveshirman** [comment]
@asjqkkkk thanks for this. I've moved already to the flutter_markdown package whilst this was being fixed. You also didn't answer my question about what specifically this does differently to that package, which I'd appreciate. Thanks.

**Comment by astral-alpaca** [comment]
It seems the problem does not exist in 2.2.0

**Comment by gaganyadav80** [comment]
The problem still exists in `2.3.2+8`
