### ISSUE TITLE
如何实现markdown的宽随着内容的长度增加而增加呢？

### ISSUE THREAD

**Issue by badboy-tian** [asjqkkkk/markdown_widget#88]
我的需求是 markdown的宽度随着内容的长度增加而增加， 当长度达到屏幕的一半的时候，markdown开始换行显示
```
Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            constraints: BoxConstraints(
              maxWidth: MediaQuery.of(context).size.width / 1.8,
            ),
            decoration: BoxDecoration(
              color: im_left_color,
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(18),
                topRight: Radius.circular(18),
                bottomRight: Radius.circular(18),
              ),
            ),
            padding: const EdgeInsets.only(
              left: 14,
              right: 14,
              top: 12,
              bottom: 12,
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Flexible(
                  child: buildMarkdown(context, item.answer),
                ),
              ],
            ),
          ),
```

```
Widget buildMarkdown(BuildContext context, String data) {
    return MarkdownWidget(
      shrinkWrap: true,
      data: data,
      config: MarkdownConfig(configs: [
        HrConfig(color: Colors.white, height: 14),
        PreConfig(
          textStyle: makeColorStyle(14.0, whiteColor),
          decoration: BoxDecoration(
            color: Colors.white.withOpacity(0.1),
            borderRadius: BorderRadius.circular(8),
          ),
        ),
        CodeConfig(style: makeColorStyle(14.0, whiteColor)),
        H1Config(style: makeColorStyle(32.0, whiteColor, fontWeight: FontWeight.bold)),
        H2Config(style: makeColorStyle(24.0, whiteColor, fontWeight: FontWeight.bold)),
        H3Config(style: makeColorStyle(20.0, whiteColor, fontWeight: FontWeight.bold)),
        H4Config(style: makeColorStyle(16.0, whiteColor, fontWeight: FontWeight.bold)),
        H5Config(style: makeColorStyle(16.0, whiteColor, fontWeight: FontWeight.bold)),
        H6Config(style: makeColorStyle(16.0, whiteColor, fontWeight: FontWeight.bold)),
        PConfig(textStyle: makeColorStyle(14.0, whiteColor)),
      ]),
    );
  }
```
![image](https://user-images.githubusercontent.com/2835129/226347885-9eaf9d1e-0726-4e97-b016-ebde6c0c2bfb.png)
我想达到的效果是：
![image](https://user-images.githubusercontent.com/2835129/226348040-fead0825-900a-48d7-9fee-e3a752e7039d.png)

**Comment by asjqkkkk** [comment]
@badboy-tian 你好，目前有一部分markdown_widget的组件默认是占满全部宽度的，这导致了上面的布局问题，不过看到上面的使用场景，我认为有必要加上一些办法来让使用者轻松的选择宽度模式
这个功能不是太复杂，不过需要一定的时间去开发，我应该会在下个版本加上这个问题的解决办法

**Comment by badboy-tian** [comment]
@asjqkkkk 好的 谢谢 期待您的解决方案~

**Comment by asjqkkkk** [comment]
@badboy-tian 你好，我在后面考虑了一下，有部分组件目前实现自适应宽度可能不是太合适，比如说像下面这样的 **分割线**

---

又或者一个标题带有的分割线：

# 标题+分割线

它们都不太合适作为自适应宽度的组件，如果想让一些组件去自适应宽度，则需要去掉占全部宽度的那一部分，以标题为例，就需要像这样：

```
class YourH1Config extends H1Config{
...
  @override
  HeadingDivider? get divider => null;
}
```
其他的类似

但是你的需求可以暂时用另外一种办法来解决
`markdown_widget` 提供了 `MarkdownGenerator` 将输入文本转换为Widget list输出，使用这个输出就可以实现上面的效果，下面是一个简单的例子可供参考

```
import 'package:flutter/material.dart';
import 'package:markdown_widget/markdown_widget.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: buildMarkdown(context, "aa `bb` aaa  **cc**"),
      ),
    );
  }
}

Widget buildMarkdown(BuildContext context, String data) {
  final markdownGenerator = MarkdownGenerator(
      config: MarkdownConfig(configs: [
    HrConfig(color: Colors.white, height: 14),
  ]));
  final result = markdownGenerator.buildWidgets(data);
  return Container(
    decoration: BoxDecoration(
      color: Colors.redAccent,
      borderRadius: const BorderRadius.only(
        topLeft: Radius.circular(18),
        topRight: Radius.circular(18),
        bottomRight: Radius.circular(18),
      ),
    ),
    padding: EdgeInsets.all(8),
    child: Column(
      mainAxisSize: MainAxisSize.min,
      children: result,
    ),
  );
}

```

**Comment by badboy-tian** [comment]
解决了, 谢谢~

**Comment by coderghl** [comment]
> @badboy-tian 你好，我在后面考虑了一下，有部分组件目前实现自适应宽度可能不是太合适，比如说像下面这样的 **分割线**
> 
> 又或者一个标题带有的分割线：
> 
> # 标题+分割线
> 它们都不太合适作为自适应宽度的组件，如果想让一些组件去自适应宽度，则需要去掉占全部宽度的那一部分，以标题为例，就需要像这样：
> 
> ```
> class YourH1Config extends H1Config{
> ...
>   @override
>   HeadingDivider? get divider => null;
> }
> ```
> 
> 其他的类似
> 
> 但是你的需求可以暂时用另外一种办法来解决 `markdown_widget` 提供了 `MarkdownGenerator` 将输入文本转换为Widget list输出，使用这个输出就可以实现上面的效果，下面是一个简单的例子可供参考
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:markdown_widget/markdown_widget.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         body: buildMarkdown(context, "aa `bb` aaa  **cc**"),
>       ),
>     );
>   }
> }
> 
> Widget buildMarkdown(BuildContext context, String data) {
>   final markdownGenerator = MarkdownGenerator(
>       config: MarkdownConfig(configs: [
>     HrConfig(color: Colors.white, height: 14),
>   ]));
>   final result = markdownGenerator.buildWidgets(data);
>   return Container(
>     decoration: BoxDecoration(
>       color: Colors.redAccent,
>       borderRadius: const BorderRadius.only(
>         topLeft: Radius.circular(18),
>         topRight: Radius.circular(18),
>         bottomRight: Radius.circular(18),
>       ),
>     ),
>     padding: EdgeInsets.all(8),
>     child: Column(
>       mainAxisSize: MainAxisSize.min,
>       children: result,
>     ),
>   );
> }
> ```

I would like to know how to make a widget list optional when I use MarkdownGenerator to convert text to a widget list?

**Comment by coderghl** [comment]
我想知道如何在转化成widget list后还能支持可选择参数？ @asjqkkkk

**Comment by asjqkkkk** [comment]
> 我想知道如何在转化成widget list后还能支持可选择参数？ @asjqkkkk

这里的 **可选择参数** 是指类似于 `MarkdownConfig` 这类的配置功能吗？

**Comment by coderghl** [comment]
> > 我想知道如何在转化成widget list后还能支持可选择参数？ @asjqkkkk
> 
> 这里的 **可选择参数** 是指类似于 `MarkdownConfig` 这类的配置功能吗？

是的，就是怎么支持滑动选择复制

**Comment by asjqkkkk** [comment]
@coderghl 可以使用 `SelectionArea` 实现选中效果

**Comment by coderghl** [comment]
> 

谢谢，成功了😊
