### ISSUE TITLE
hi, how to add copy button on codeblock

### ISSUE THREAD

**Issue by badboy-tian** [asjqkkkk/markdown_widget#89]
RT, sometimes we can add a copy button on the top right of the code block. and click the copy button, the code in the codeblock will be copy~

**Comment by asjqkkkk** [comment]
Hi @badboy-tian ， there is a sample code  [code_wrapper.dart](https://github.com/asjqkkkk/markdown_widget/blob/master/example/lib/widget/code_wrapper.dart) which may be helpful

and you can also have a look with [online demo](https://asjqkkkk.github.io/markdown_widget/#/readme), it displays the copy button

**Comment by badboy-tian** [comment]
@asjqkkkk Thank you for reply. i use 
```
markdownGenerator.buildWidgets(data)
```
How to enable the mouse to freely select markdown text and copy text

**Comment by asjqkkkk** [comment]
@badboy-tian  you can use `SelectionArea`

**Comment by fei1025** [comment]
> 你好@badboy-tian，有一个示例代码 [code_wrapper.dart](https://github.com/asjqkkkk/markdown_widget/blob/master/example/lib/widget/code_wrapper.dart)这可能会有所帮助
> 
> 你也可以看看[在线演示](https://asjqkkkk.github.io/markdown_widget/#/readme)，它显示了复制按钮
你好,能问下如何用吗? 我看在线演示没有如何使用的
