### ISSUE TITLE
How do you calculate the height of the content?

### ISSUE THREAD

**Issue by NusLookingForYou** [asjqkkkk/markdown_widget#93]
How do we calculate the height of the content when we use markdown?

**Comment by asjqkkkk** [comment]
Hi @NusLookingForYou , `markdown_widget` can be rendered by `ListView` or `Column`,  If it's rendered by ListView, its height is infinite, but if it's rendered by Column, its height can be calculated based on the LayoutBuilder.

**Comment by bravekingzhang** [comment]
@asjqkkkk use Column warp  solve my problems ，thanks you very much
