### ISSUE TITLE
Overriding Markdown Config breaks bold and italic markdown tags

### ISSUE THREAD

**Issue by NicolasLaube** [asjqkkkk/markdown_widget#98]
**Description of the bug**

When overriding markdown's config, the bold and italic markdown tags don't work anymore.
I need to override the config because the text size is too small...

**To Reproduce**

Here is my widget:

```
 MarkdownWidget(
        padding: EdgeInsets.zero,
        data: rawText,
        physics: const NeverScrollableScrollPhysics(),
        selectable: false,
        shrinkWrap: true,
        config: MarkdownConfig(
          configs: [
            PConfig(
              textStyle: Theme.of(context).textTheme.bodySmall!,
            ),
            H1Config(
              style: Theme.of(context).textTheme.headlineLarge!,
            ),
          ],
        ),
        markdownGeneratorConfig: MarkdownGeneratorConfig(
          generators: _getGenerators(), // can be replaced by [] to reproduce error
          textGenerator: (node, config, visitor) => CustomTextNode( // your class
            node.textContent,
            config,
            visitor,
          ),
          inlineSyntaxList: [LatexSyntax()],
        ),
      )
```

**Screenshots**

Without overriding markdown's config, here is what I get:

<img width="722" alt="image" src="https://user-images.githubusercontent.com/45005101/233644460-bc1a3903-e479-4af7-9fe1-debfca60ba8f.png">

When I override the config:

<img width="722" alt="image" src="https://user-images.githubusercontent.com/45005101/233644215-b20f0672-1140-43cf-b60a-06eb9a64fa81.png">

**Environment:**

Package version: ` markdown_widget: ^2.1.0`

Result of `flutter doctor`:

```
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.0)
[✓] VS Code (version 1.71.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Source data**

My example text is the following:
`**Pour mettre un text en gras,** placez votre texte entre \"doubles astérix \*\*\".`

**Comment by asjqkkkk** [comment]
Hi @NicolasLaube  thanks for your issue!
This is a bug, I'll fix it next version

**Comment by asjqkkkk** [comment]
Hi @NicolasLaube , the next release may require fixing several more bugs or adding new features, and the exact number is currently uncertain. If you urgently need this fix, you can try making some modifications based on [this reference](https://github.com/asjqkkkk/markdown_widget/commit/078a74e3d32e56c3cd448d874c1f816e49223b76) or use the version of this commit
